#Combine all NDL features into a dataframe

##Speech-timing NDL

In [ ]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [ ]:
catAcousticDF = pd.read_csv('catAcoustic_Preprocessed_May1.csv')
catAcousticDF.head()

,Sample_ID,speechrate,Average Syllable Duration,Articulation rate,Speech-to-pause ratio,# of pauses,Mean Pause Duration,Variability of Pause Duration,# words/min,# propositions/min
0,BILP006,2.249347,0.222581,4.492747,1.002651,99,1.191510,1.127368,52.855390,22.065842
1,BILP007,2.035069,0.226106,4.422696,0.852340,38,1.706378,2.344119,56.434695,26.678220
2,BILP008,3.911343,0.198854,5.028811,3.500183,21,0.727200,0.156940,168.676662,78.838005
3,BILP009,3.083426,0.247910,4.033720,3.244706,38,0.735135,0.192954,39.495565,16.629712
4,BILP010,2.597004,0.195858,5.105736,1.035186,68,1.194507,0.735932,63.359528,33.889980

In [ ]:
spaAcousticDF = pd.read_csv('spaAcoustic_Preprocessed_May1.csv')
spaAcousticDF.head()

,Sample_ID,Mean Pause Duration,Variability of Pause Duration,speechrate,Average Syllable Duration,Articulation rate,Speech-to-pause ratio,# of pauses,# words/min,# propositions/min
0,BILP006,1.213500,1.288158,2.188507,0.235668,4.243264,1.065092,129,75.194846,35.352801
1,BILP007,1.278933,0.711372,2.396601,0.249712,4.004617,1.490409,31,52.746149,21.977562
2,BILP008,0.703200,0.092403,4.005635,0.204134,4.898749,4.485021,21,140.780559,59.890072
3,BILP009,0.767030,0.247311,3.375352,0.230690,4.334817,3.517953,34,67.157266,29.905970
4,BILP010,1.568102,1.750063,1.809513,0.227399,4.397558,0.699181,56,39.005055,15.280331

In [ ]:
import pandas as pd
demoDF = pd.read_csv('bilingual_WAB_lv_nfv_primary_sheet(Parent_Sheet).csv',encoding='ISO-8859-1')
demoDF.head()

,IDs,DomLang,"Catalan transcription copied to manuscripts folder 20240318 (13 non dom, 23 dom)",Age,variant,HSP/BC ID,Site,Comments,Recorded in,Logistics in recording,...,Pre-Tx_Date (DDMMYYY),Date_of_MRI,Link to folder for MRI,MRI uploaded to box,MRI Format,DOB (m/d/y),BACC_MRI_STATUS_20250320,path_hsp_cluster,closest_mri_cluster,Unnamed: 22
0,BILP006,Spanish,y,67,lv,1807086.0,HSP,NaN,ZOOM .mp4,ZOOM recording (different laptops),...,9/2/2020,11/3/2020,MRI folder:,Y,.nii,4/25/1957,in-box,NaN,NaN,NaN
1,BILP007,Catalan,y,68,lv,70054820.0,BC,Not added in the analysis? why? Decided now to...,ZOOM .mp5,ZOOM recording (different laptops),...,12/28/2020,9/29/2020,NaN,Y,.rar,7/27/1956,BC,NaN,NaN,NaN
2,BILP008,Catalan,y,79,lv,525199.0,HSP,NaN,ZOOM .mp4,ZOOM recording (different laptops),...,1/27/2021,2/16/2021,NaN,Y,.nii,6/2/1945,in-box,NaN,NaN,NaN
3,BILP009,Spanish,y,76,lv,80018295.0,BC,NaN,ZOOM .mp4,ZOOM recording (different laptops),...,2/8/2021,1/19/2021,NaN,Y,.rar,7/3/1948,BC,NaN,NaN,NaN
4,BILP010,Catalan,y,82,lv,1741141.0,HSP,NaN,ZOOM .mp4,ZOOM recording (different laptops),...,3/31/2021,11/16/2021 (no se presento),NaN,NaN,NaN,6/29/1942,Sí,/theshire/nicore/DATA/SPIN/sourcedata/1741141/...,20240113,NaN

In [ ]:
demoDF[['IDs ', 'DomLang']]
spaNotDominantIDs = list(demoDF[demoDF['DomLang'] == 'Catalan']['IDs '])
catNotDominantIDs = list(demoDF[demoDF['DomLang'] == 'Spanish']['IDs '])

In [ ]:
print(spaNotDominantIDs)
print(catNotDominantIDs)

['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BISE010', 'BISE011', 'BISE014', 'BILP025', 'BISE019', 'BILP027', 'BILP028', 'BIOBS004', 'BILP029', 'BIOBS003', 'BIOBS005']
['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BILP024', 'BISE018', 'BILP026']

In [ ]:
len(spaNotDominantIDs), len(catNotDominantIDs)

(23, 11)

In [ ]:
spaNotDomAcousticDF = spaAcousticDF[spaAcousticDF['Sample_ID'].isin(spaNotDominantIDs)]
catNotDomAcousticDF = catAcousticDF[catAcousticDF['Sample_ID'].isin(catNotDominantIDs)]

In [ ]:
spaNotDomAcousticDF.shape, catNotDomAcousticDF.shape

((23, 10), (11, 10))

In [ ]:
notDomAcousticDF = pd.concat([spaNotDomAcousticDF, catNotDomAcousticDF])
notDomAcousticDF.shape

(34, 10)

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

notDomAcousticY = notDomAcousticDF['Sample_ID'].apply(getClass)
data_Y = notDomAcousticY

In [ ]:
notDomAcousticY

1      lv
2      lv
4      lv
5      lv
6      lv
8      lv
9      lv
10     lv
11     lv
12     lv
13     lv
14     lv
17     lv
19     lv
20     lv
21     lv
22     lv
23    nfv
24     lv
27    nfv
28    nfv
30    nfv
33    nfv
0      lv
3      lv
7      lv
15     lv
16     lv
18     lv
25    nfv
26    nfv
29    nfv
31    nfv
32    nfv
Name: Sample_ID, dtype: object

In [ ]:
notDomAcousticDF.head()

,Sample_ID,Mean Pause Duration,Variability of Pause Duration,speechrate,Average Syllable Duration,Articulation rate,Speech-to-pause ratio,# of pauses,# words/min,# propositions/min
1,BILP007,1.278933,0.711372,2.396601,0.249712,4.004617,1.490409,31,52.746149,21.977562
2,BILP008,0.703200,0.092403,4.005635,0.204134,4.898749,4.485021,21,140.780559,59.890072
4,BILP010,1.568102,1.750063,1.809513,0.227399,4.397558,0.699181,56,39.005055,15.280331
5,BILP011,1.805333,1.299492,2.296170,0.235840,4.240168,1.181158,25,55.235047,20.951225
6,BILP012,1.589731,1.869004,1.405752,0.240071,4.165438,0.509389,68,36.201234,11.196258

##Speech-timing DL

In [ ]:
spaDominantIDs = list(demoDF[demoDF['DomLang'] == 'Spanish']['IDs '])
catDominantIDs = list(demoDF[demoDF['DomLang'] == 'Catalan']['IDs '])

In [ ]:
print(spaDominantIDs)
print(catDominantIDs)

['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BILP024', 'BISE018', 'BILP026']
['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BISE010', 'BISE011', 'BISE014', 'BILP025', 'BISE019', 'BILP027', 'BILP028', 'BIOBS004', 'BILP029', 'BIOBS003', 'BIOBS005']

In [ ]:
len(spaDominantIDs), len(catDominantIDs)

(11, 23)

In [ ]:
spaDomAcousticDF = spaAcousticDF[spaAcousticDF['Sample_ID'].isin(spaDominantIDs)]
catDomAcousticDF = catAcousticDF[catAcousticDF['Sample_ID'].isin(catDominantIDs)]

In [ ]:
spaDomAcousticDF.shape, catDomAcousticDF.shape

((11, 10), (23, 10))

In [ ]:
domAcousticDF = pd.concat([spaDomAcousticDF, catDomAcousticDF])
domAcousticDF.shape

(34, 10)

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

domAcousticY = domAcousticDF['Sample_ID'].apply(getClass)
data_Y = domAcousticY

In [ ]:
domAcousticDF.head()

,Sample_ID,Mean Pause Duration,Variability of Pause Duration,speechrate,Average Syllable Duration,Articulation rate,Speech-to-pause ratio,# of pauses,# words/min,# propositions/min
0,BILP006,1.21350,1.288158,2.188507,0.235668,4.243264,1.065092,129,75.194846,35.352801
3,BILP009,0.76703,0.247311,3.375352,0.230690,4.334817,3.517953,34,67.157266,29.905970
7,BILP013,0.82240,0.232953,3.643164,0.197024,5.075535,2.543450,61,103.289714,43.923865
15,BILP022,1.76680,1.807666,1.878094,0.275466,3.630218,1.071896,41,57.777006,26.225024
16,BILP024,1.75040,2.137329,1.819027,0.239939,4.167724,0.774484,61,55.375693,24.146378

##Word params NDL

In [ ]:
import pandas as pd

In [ ]:
spaNotDomLingDF = pd.read_csv('SPA_NotDom_LinguisticFeatures.csv')
#Rename Frequency per million:Espal average to Frequency per million average
spaNotDomLingDF.rename(columns={'Frequency per million:Espal average': 'Frequency per million average'}, inplace=True)
spaNotDomLingDF.head()

,Sample_ID,file,# of words,# of sentences,Average sentence length,POS_COUNT:ADJ,POS_COUNT:ADP,POS_COUNT:ADV,POS_COUNT:AUX,POS_COUNT:CCONJ,...,# gender agreement errors,# gender agreement errors: only DET,# gender agreement errors per 100 nouns,# gender agreement errors (only DET) per 100 nouns,# number agreement errors,# number agreement errors: only DET,# number agreement errors per 100 nouns,# number agreement errors (only DET) per 100 nouns,Phonotactic Probability Unigram Mean,Phonotactic Probability Bigram Mean
0,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,84.0,9.0,9.333333,1.0,8.0,8.0,8.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.256325,1.024675
1,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,181.0,18.0,10.055556,4.0,20.0,14.0,15.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.242080,1.022997
2,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,97.0,17.0,5.705882,2.0,8.0,11.0,14.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.224247,1.020762
3,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,87.0,11.0,7.909091,1.0,8.0,4.0,11.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.250709,1.025275
4,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,97.0,17.0,5.705882,1.0,6.0,5.0,16.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.236937,1.023662

In [ ]:
wordParams = ['Frequency per million average', 'Verb Frequency per million average',
'Noun Frequency per million average','% high frequency verbs', 'Word length by syllables average',
 'Concreteness average','Age of Acquisition min average',  'Word length by phonemes average',
  #'Phonotactic Probability Unigram Mean',  'Phonotactic Probability Bigram Mean'
 ]

In [ ]:
spaNotDomWordParamsDF = spaNotDomLingDF[['Sample_ID'] + wordParams]
spaNotDomWordParamsDF.head()

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,10565.137968,340.977688,216.682383,0.500000,1.722892,3.072260,1.086420,3.710843
1,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,10520.856982,261.118388,142.557131,0.285714,1.727778,3.011589,1.169492,3.661111
2,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,8211.377281,142.034389,100.971598,0.285714,1.687500,3.026937,1.106383,3.593750
3,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,8742.082285,124.597326,177.582116,0.363636,1.735632,3.090308,1.139535,3.758621
4,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,8591.034907,38.193465,180.555725,0.000000,1.652632,3.075801,1.138298,3.589474

In [ ]:
wordParams = ['Frequency per million average', 'Verb Frequency per million average',
'Noun Frequency per million average','% high frequency verbs', 'Word length by syllables average',
 'Concreteness average','Age of Acquisition min average',  'Word length by phonemes average',
  #'Phonotactic Probability Unigram Mean',  'Phonotactic Probability Bigram Mean'
 ]

In [ ]:
catNotDomLingDF = pd.read_csv('CAT_NotDom_LinguisticFeatures.csv')
catNotDomWordParamsDF = catNotDomLingDF[['Sample_ID'] + wordParams]
print(catNotDomWordParamsDF.shape)
catNotDomWordParamsDF.head()

(11, 9)

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,8140.368511,4418.687848,316.895615,0.647059,1.527174,2.965473,2.888889,3.062802
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,7808.872582,1985.139067,288.542286,0.533333,1.402985,3.018929,2.500000,2.894737
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,8352.394833,3039.235205,355.917184,0.452381,1.502203,2.961231,3.363636,3.007692
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,8496.780863,2321.240289,229.730634,0.466667,1.556017,2.942881,3.434783,3.228464
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,7977.482525,1650.298233,290.605300,0.483871,1.487654,2.966320,3.789474,2.950549

In [ ]:
notDomWordParamsDF = pd.concat([catNotDomWordParamsDF, spaNotDomWordParamsDF])
print(notDomWordParamsDF.shape)
notDomWordParamsDF.head()

(34, 9)

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,8140.368511,4418.687848,316.895615,0.647059,1.527174,2.965473,2.888889,3.062802
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,7808.872582,1985.139067,288.542286,0.533333,1.402985,3.018929,2.500000,2.894737
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,8352.394833,3039.235205,355.917184,0.452381,1.502203,2.961231,3.363636,3.007692
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,8496.780863,2321.240289,229.730634,0.466667,1.556017,2.942881,3.434783,3.228464
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,7977.482525,1650.298233,290.605300,0.483871,1.487654,2.966320,3.789474,2.950549

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [ ]:
notDomWordParamsDF['Class'] = notDomWordParamsDF['Sample_ID'].apply(getClass)
notDomWordParamsDF

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average,Class
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,8140.368511,4418.687848,316.895615,0.647059,1.527174,2.965473,2.888889,3.062802,lv
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,7808.872582,1985.139067,288.542286,0.533333,1.402985,3.018929,2.500000,2.894737,lv
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,8352.394833,3039.235205,355.917184,0.452381,1.502203,2.961231,3.363636,3.007692,lv
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,8496.780863,2321.240289,229.730634,0.466667,1.556017,2.942881,3.434783,3.228464,lv
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,7977.482525,1650.298233,290.605300,0.483871,1.487654,2.966320,3.789474,2.950549,lv
5,BILP026_BACC012_PicnicScene_Cat_Obs1_20240327_...,8927.350823,3592.621619,257.912357,0.619048,1.460177,2.862349,2.571429,2.765152,lv
6,BISE004_PreTx_Cat_WABPicnic_Coded.flo.cex,6987.748970,172.621400,107.339158,0.200000,1.712121,3.144839,3.272727,3.564103,nfv
7,BISE005_PreTx_Cat_WABPicnic_Coded.flo.cex,7805.031750,3787.842692,267.922350,0.500000,1.527778,3.070446,2.714286,2.860465,nfv
8,BISE013_BACC001_PicnicScene_Cat_Pre_20230426_C...,7795.345875,3293.356667,306.267412,0.444444,1.562500,3.075759,3.375000,3.255814,nfv
9,BISE016_BACC014_PicnicScene_Cat_Pre_20240110_C...,9533.747548,2984.000944,287.052318,0.444444,1.663462,3.024870,4.000000,3.435897,nfv
10,BISE018_BACC019_PicnicScene_Cat_Pre_20240219_C...,8341.025635,3877.290700,178.871071,0.500000,1.538462,3.147834,3.300000,3.033333,nfv
0,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,10565.137968,340.977688,216.682383,0.500000,1.722892,3.072260,1.086420,3.710843,lv
1,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,10520.856982,261.118388,142.557131,0.285714,1.727778,3.011589,1.169492,3.661111,lv
2,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,8211.377281,142.034389,100.971598,0.285714,1.687500,3.026937,1.106383,3.593750,lv
3,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,8742.082285,124.597326,177.582116,0.363636,1.735632,3.090308,1.139535,3.758621,lv
4,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,8591.034907,38.193465,180.555725,0.000000,1.652632,3.075801,1.138298,3.589474,lv
5,BILP014_PreTx_Spa_WABPicnic_Coded.flo.cex,12287.391631,335.718377,144.290475,0.450000,1.626263,3.005099,1.135417,3.474747,lv
6,BILP015_PreTx_Spa_WABPicnic_Coded.flo.cex,11115.048370,221.341668,230.740460,0.333333,1.759494,3.036282,1.067568,3.784810,lv
7,BILP017_PreTx_Spa_WABPicnic_Coded.flo.cex,9133.065034,157.325056,134.275351,0.523810,1.798611,2.989840,1.154412,3.979167,lv
8,BILP018_PreTx_Spa_WABPicnic_Coded.flo.cex,10331.553491,219.375589,186.906082,0.675676,1.642276,2.953180,1.116667,3.475610,lv
9,BILP019_PreTx_Spa_WABPicnic_Coded.flo.cex,9316.883077,142.215926,84.727072,0.315789,1.590551,2.964174,1.048780,3.267717,lv
10,BILP020_PreTx_Spa_WABPicnic_Coded.flo.cex,9261.463542,459.349712,156.547036,0.692308,1.640777,3.038121,1.070707,3.563107,lv
11,BILP021_PreTx_Spa_WABPicnic_Coded.flo.cex,6548.642302,163.971537,234.539663,0.375000,1.735849,3.053810,1.107843,3.707547,lv
12,BILP025_BACC020_PicnicScene_Spa_Pre_20240507_C...,8874.467086,308.478734,115.081784,0.485714,1.700599,2.992448,1.187302,3.634731,lv
13,BILP027_BACC81_PicnicScene_Spa_Pre_20240522_Co...,9797.305808,225.495529,218.737021,0.370370,1.655340,2.972583,1.171569,3.631068,lv
14,BILP028_BACC116_PicnicScene_Spa_Pre_20240916_C...,9400.558747,117.406740,229.920569,0.250000,1.687296,2.900454,1.142857,3.732899,lv
15,BILP029_BACC109_PicnicScene_Spa_Pre_20241009_C...,11896.947820,207.219355,136.788147,0.285714,1.762712,3.056461,1.017857,3.847458,lv
16,BIOBS003_BACC111_PicnicScene_Spa_Obs1_20241030...,9597.989201,345.934924,178.032073,0.454545,1.718447,2.959508,1.088235,3.669903,lv
17,BIOBS004_BACC50_PicnicScene_Spa_EB1_20240904_C...,7331.173538,405.948488,233.200624,0.400000,1.547619,3.000528,1.166667,3.333333,nfv
18,BIOBS005_BACC091_PicnicScene_Spa_EB1_20241023_...,11797.990690,180.427074,170.697773,0.416667,1.737288,3.112717,1.100000,3.737288,lv
19,BISE010_PreTx_Spa_WABPicnic_Coded.flo.cex,10576.864814,34.552418,145.805418,0.142857,1.811594,3.168782,1.075758,3.695652,nfv
20,BISE011_PreTx_Spa_WABPicnic_Coded.flo.cex,11725.807729,300.604026,93.253931,0.333333,1.763158,3.167396,1.093333,3.723684,nfv
21,BISE014_BACC005_PicnicScene_Spa_Pre_20230629_C...,11034.929816,125.612982,115.343739,0.318182,1.808511,3.114101,1.242152,4.063830,nfv
22,BISE019_PreTx_Spa_WABPicnic_Coded.flo.cex,9003.344615,290.431084,172.251231,0.285714,1.767857,3.267438,1.037037,3.767857,nfv

##Word params DL

In [ ]:
import pandas as pd

In [ ]:
spaDomLingDF = pd.read_csv('SPA_Dom_LinguisticFeatures.csv')
#Rename Frequency per million:Espal average to Frequency per million average
spaDomLingDF.rename(columns={'Frequency per million:Espal average': 'Frequency per million average'}, inplace=True)
spaDomLingDF.head()

,Sample_ID,file,# of words,# of sentences,Average sentence length,POS_COUNT:ADJ,POS_COUNT:ADP,POS_COUNT:ADV,POS_COUNT:AUX,POS_COUNT:CCONJ,...,# gender agreement errors,# gender agreement errors: only DET,# gender agreement errors per 100 nouns,# gender agreement errors (only DET) per 100 nouns,# number agreement errors,# number agreement errors: only DET,# number agreement errors per 100 nouns,# number agreement errors (only DET) per 100 nouns,Phonotactic Probability Unigram Mean,Phonotactic Probability Bigram Mean
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,402.0,47.0,8.553191,8.0,39.0,64.0,45.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.223483,1.019752
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,128.0,16.0,8.000000,2.0,9.0,12.0,16.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.205589,1.017614
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,301.0,29.0,10.379310,12.0,32.0,22.0,28.0,24.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.000154,0.0,1.245204,1.024621
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,141.0,10.0,14.100000,1.0,18.0,13.0,9.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.255858,1.024531
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,172.0,20.0,8.600000,3.0,13.0,17.0,19.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.235113,1.022066

In [ ]:
wordParams = ['Frequency per million average', 'Verb Frequency per million average',
'Noun Frequency per million average','% high frequency verbs', 'Word length by syllables average',
 'Concreteness average','Age of Acquisition min average',  'Word length by phonemes average',
  #'Phonotactic Probability Unigram Mean',  'Phonotactic Probability Bigram Mean'
 ]

In [ ]:
print(list(spaDomLingDF.columns))

['Sample_ID', 'file', '# of words', '# of sentences', 'Average sentence length', 'POS_COUNT:ADJ', 'POS_COUNT:ADP', 'POS_COUNT:ADV', 'POS_COUNT:AUX', 'POS_COUNT:CCONJ', 'POS_COUNT:DET', 'POS_COUNT:INTJ', 'POS_COUNT:NOUN', 'POS_COUNT:NUM', 'POS_COUNT:PART', 'POS_COUNT:PRON', 'POS_COUNT:PROPN', 'POS_COUNT:SCONJ', 'POS_COUNT:VERB', 'POS_Proportion:ADJ', 'POS_Proportion:ADP', 'POS_Proportion:ADV', 'POS_Proportion:AUX', 'POS_Proportion:CCONJ', 'POS_Proportion:DET', 'POS_Proportion:INTJ', 'POS_Proportion:NOUN', 'POS_Proportion:NUM', 'POS_Proportion:PART', 'POS_Proportion:PRON', 'POS_Proportion:PROPN', 'POS_Proportion:SCONJ', 'POS_Proportion:VERB', 'POS_Proportion:CONJ', 'VerbForm_COUNT:Fin', 'VerbForm_COUNT:Ger', 'VerbForm_COUNT:Inf', 'VerbForm_COUNT:Part', 'VerbForm_Proportion:Fin', 'VerbForm_Proportion:Ger', 'VerbForm_Proportion:Inf', 'VerbForm_Proportion:Part', 'Mood_COUNT:Ind', 'Mood_COUNT:Imp', 'Mood_COUNT:Sub', 'Mood_COUNT:Cnd', 'Mood_Proportion:Ind', 'Mood_Proportion:Imp', 'Mood_Proportion:Sub', 'Mood_Proportion:Cnd', 'Masc_NOUN_COUNT', 'Fem_NOUN_COUNT', 'Masc_ADJ_COUNT', 'Fem_ADJ_COUNT', 'Masc_DET_COUNT', 'Fem_DET_COUNT', 'Mood_AUX_COUNT:Ind', 'Mood_AUX_COUNT:Imp', 'Mood_AUX_COUNT:Sub', 'Mood_AUX_COUNT:Cnd', 'Number_AUX_COUNT:Sing', 'Number_AUX_COUNT:Plur', 'Number_AUX_COUNT:Plur,Sing', 'Person_AUX_COUNT:1', 'Person_AUX_COUNT:2', 'Person_AUX_COUNT:3', 'Tense_AUX_COUNT:Pres', 'Tense_AUX_COUNT:Imp', 'Tense_AUX_COUNT:Fut', 'Tense_AUX_COUNT:Past', 'Mood_VERB_COUNT:Ind', 'Mood_VERB_COUNT:Imp', 'Mood_VERB_COUNT:Sub', 'Mood_VERB_COUNT:Cnd', 'Number_VERB_COUNT:Sing', 'Number_VERB_COUNT:Plur', 'Number_VERB_COUNT:Plur,Sing', 'Person_VERB_COUNT:1', 'Person_VERB_COUNT:2', 'Person_VERB_COUNT:3', 'Tense_VERB_COUNT:Pres', 'Tense_VERB_COUNT:Imp', 'Tense_VERB_COUNT:Fut', 'Tense_VERB_COUNT:Past', '# of clitics', '# of clitics:Case=Acc', '# of clitics:Case=Dat', '# of clitics:Masc', '# of clitics:Fem', 'Average clitics per sentence', '# of relative pronouns', '# finite verbs per sentence', '# verbs per sentence', '# coordinate clauses', '# coordinate clauses per sentence', 'DEP_COUNT:acl', 'DEP_COUNT:acomp', 'DEP_COUNT:advcl', 'DEP_COUNT:advmod', 'DEP_COUNT:agent', 'DEP_COUNT:amod', 'DEP_COUNT:appos', 'DEP_COUNT:attr', 'DEP_COUNT:aux', 'DEP_COUNT:auxpass', 'DEP_COUNT:case', 'DEP_COUNT:cc', 'DEP_COUNT:ccomp', 'DEP_COUNT:compound', 'DEP_COUNT:conj', 'DEP_COUNT:cop', 'DEP_COUNT:csubj', 'DEP_COUNT:csubjpass', 'DEP_COUNT:dative', 'DEP_COUNT:dep', 'DEP_COUNT:det', 'DEP_COUNT:dobj', 'DEP_COUNT:expl', 'DEP_COUNT:intj', 'DEP_COUNT:mark', 'DEP_COUNT:meta', 'DEP_COUNT:neg', 'DEP_COUNT:nn', 'DEP_COUNT:npmod', 'DEP_COUNT:nsubj', 'DEP_COUNT:nsubjpass', 'DEP_COUNT:oprd', 'DEP_COUNT:obj', 'DEP_COUNT:obl', 'DEP_COUNT:pcomp', 'DEP_COUNT:pobj', 'DEP_COUNT:poss', 'DEP_COUNT:preconj', 'DEP_COUNT:prep', 'DEP_COUNT:prt', 'DEP_COUNT:punct', 'DEP_COUNT:quantmod', 'DEP_COUNT:relcl', 'DEP_COUNT:root', 'DEP_COUNT:xcomp', 'DEP_Proportion:acl', 'DEP_Proportion:acomp', 'DEP_Proportion:advcl', 'DEP_Proportion:advmod', 'DEP_Proportion:agent', 'DEP_Proportion:amod', 'DEP_Proportion:appos', 'DEP_Proportion:attr', 'DEP_Proportion:aux', 'DEP_Proportion:auxpass', 'DEP_Proportion:case', 'DEP_Proportion:cc', 'DEP_Proportion:ccomp', 'DEP_Proportion:compound', 'DEP_Proportion:conj', 'DEP_Proportion:cop', 'DEP_Proportion:csubj', 'DEP_Proportion:csubjpass', 'DEP_Proportion:dative', 'DEP_Proportion:dep', 'DEP_Proportion:det', 'DEP_Proportion:dobj', 'DEP_Proportion:expl', 'DEP_Proportion:intj', 'DEP_Proportion:mark', 'DEP_Proportion:meta', 'DEP_Proportion:neg', 'DEP_Proportion:nn', 'DEP_Proportion:npmod', 'DEP_Proportion:nsubj', 'DEP_Proportion:nsubjpass', 'DEP_Proportion:oprd', 'DEP_Proportion:obj', 'DEP_Proportion:obl', 'DEP_Proportion:pcomp', 'DEP_Proportion:pobj', 'DEP_Proportion:poss', 'DEP_Proportion:preconj', 'DEP_Proportion:prep', 'DEP_Proportion:prt', 'DEP_Proportion:punct', 'DEP_Proportion:quantmod', 'DEP_Proportion:relcl', 'DEP_Proportion:root', 'DEP_Proportion:xcomp', 'Grammar Complexity Index', 'Noun to Verb ratio', '# of unique words', 'Type Token Ratio', 'Moving Average Type Token Ratio, n=5', 'Moving Average Type Token Ratio, n=10', 'Moving Average Type Token Ratio, n=15', 'Propositional Density', '# of fillers', 'Proportion Fillers', 'Proportion Repetitions', 'Open Closed Words Ratio', 'Age of Acquisition min average', 'Age of Acquisition max average', 'Age of Acquisition mean average', 'Age of Acquisition stdev average', 'NHF average', 'Levenshtein_N average', 'MBF_To_pos average', 'MBF_To_abs average', 'MBF_Ty_pos average', 'MBF_Ty_abs average', 'Word length by phonemes average', 'Masculine noun length by phonemes average', 'Feminine noun length by phonemes average', 'Frequency per million average', 'Familiarity average', 'Imageability average', 'Concreteness:Espal average', 'Word length by syllables average', 'Zipf average', 'Noun Frequency per million average', 'Verb Frequency per million average', '# high frequency verbs', '% high frequency verbs', '# low frequency verbs', '% low frequency verbs', 'Concreteness average', 'Prevalence average', 'Suboordination Main Verb Implied numerator', 'Suboordination Main Verb Implied', 'Suboordination With Two Finite Verbs numerator', 'Suboordination With Two Finite Verbs', '# gender agreement errors', '# gender agreement errors: only DET', '# gender agreement errors per 100 nouns', '# gender agreement errors (only DET) per 100 nouns', '# number agreement errors', '# number agreement errors: only DET', '# number agreement errors per 100 nouns', '# number agreement errors (only DET) per 100 nouns', 'Phonotactic Probability Unigram Mean', 'Phonotactic Probability Bigram Mean']

In [ ]:
spaDomWordParamsDF = spaDomLingDF[['Sample_ID'] + wordParams]
spaDomWordParamsDF.head()

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,10089.657314,160.826300,177.565780,0.300000,1.549751,2.893011,1.101266,3.253731
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,10232.391784,405.579276,95.405180,0.388889,1.609375,3.020125,1.102362,3.390625
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,10693.611268,213.673143,201.699784,0.363636,1.676667,3.034649,1.103448,3.600000
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,10947.149415,185.186031,206.776077,0.411765,1.637681,3.034450,1.154412,3.572464
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,10649.942109,281.570663,150.461315,0.440000,1.784884,2.981626,1.145455,3.726744

In [ ]:
spaDomWordParamsDF.shape

(11, 9)

In [ ]:
wordParams = ['Frequency per million average', 'Verb Frequency per million average',
'Noun Frequency per million average','% high frequency verbs', 'Word length by syllables average',
 'Concreteness average','Age of Acquisition min average',  'Word length by phonemes average',
 # 'Phonotactic Probability Unigram Mean',  'Phonotactic Probability Bigram Mean'
 ]

In [ ]:
catDomLingDF = pd.read_csv('CAT_Dom_LinguisticFeatures.csv')
catDomWordParamsDF = catDomLingDF[['Sample_ID'] + wordParams]
print(catDomWordParamsDF.shape)
catDomWordParamsDF.head()

(23, 9)

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP007_Cat_PicnicScene_Post_coded.flo.cex,7192.626441,3374.507056,426.677611,0.777778,1.500000,2.955839,3.375000,3.136364
1,BILP008_PreTx_Cat_WABPicnic_Coded.flo.cex,8499.389404,3182.077500,337.797286,0.500000,1.637427,2.999467,3.071429,3.342391
2,BILP010_PreTx_Cat_WABPicnic_Coded.flo.cex,7732.124188,2331.383436,355.122000,0.307692,1.460606,2.896390,2.555556,3.132948
3,BILP011_PicnicScene_Cat_Pre_Coded.flo.cex,8729.005458,4146.585364,280.768773,0.636364,1.625000,3.101160,3.166667,3.376623
4,BILP012_PreTx_Cat_WABPicnic_Coded.flo.cex,6464.167400,3851.494500,312.150444,0.428571,1.515789,3.008603,2.500000,3.213592

In [ ]:
domWordParamsDF = pd.concat([spaDomWordParamsDF, catDomWordParamsDF])
print(domWordParamsDF.shape)
domWordParamsDF.head()

(34, 9)

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,10089.657314,160.826300,177.565780,0.300000,1.549751,2.893011,1.101266,3.253731
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,10232.391784,405.579276,95.405180,0.388889,1.609375,3.020125,1.102362,3.390625
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,10693.611268,213.673143,201.699784,0.363636,1.676667,3.034649,1.103448,3.600000
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,10947.149415,185.186031,206.776077,0.411765,1.637681,3.034450,1.154412,3.572464
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,10649.942109,281.570663,150.461315,0.440000,1.784884,2.981626,1.145455,3.726744

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [ ]:
domWordParamsDF['Class'] = domWordParamsDF['Sample_ID'].apply(getClass)
domWordParamsDF.head()

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average,Class
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,10089.657314,160.826300,177.565780,0.300000,1.549751,2.893011,1.101266,3.253731,lv
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,10232.391784,405.579276,95.405180,0.388889,1.609375,3.020125,1.102362,3.390625,lv
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,10693.611268,213.673143,201.699784,0.363636,1.676667,3.034649,1.103448,3.600000,lv
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,10947.149415,185.186031,206.776077,0.411765,1.637681,3.034450,1.154412,3.572464,lv
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,10649.942109,281.570663,150.461315,0.440000,1.784884,2.981626,1.145455,3.726744,lv

##Linguistic NDL

###SpaNotDom

In [ ]:
import pandas as pd

In [ ]:
lingFeatsOfInterest = ['file'] + ['# of words', 'Type Token Ratio', 'Noun to Verb ratio', 'Propositional Density','Open Closed Words Ratio',  'Average sentence length', 'Suboordination Main Verb Implied','Proportion Fillers' ]

In [ ]:
def simplifyID(id):
  return id.split('_')[0]

In [ ]:
spaNotDomLingDF = pd.read_csv('SPA_NotDom_LinguisticFeatures.csv')
spaNotDomLingDF = spaNotDomLingDF[lingFeatsOfInterest]
spaNotDomLingDF['file'] = spaNotDomLingDF['file'].apply(simplifyID)
#rename 'file' column to 'File' using .rename
spaNotDomLingDF.rename(columns={'file': 'File'}, inplace=True)
spaNotDomLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers
0,BILP007,84.0,0.559524,1.285714,0.416667,0.820000,9.333333,0.888889,0.076923
1,BILP008,181.0,0.530387,1.250000,0.425414,0.771429,10.055556,0.777778,0.026882
2,BILP010,97.0,0.608247,1.000000,0.391753,0.594203,5.705882,0.294118,0.118182
3,BILP011,87.0,0.643678,1.818182,0.379310,0.666667,7.909091,0.545455,0.033333
4,BILP012,97.0,0.567010,1.909091,0.309278,0.487179,5.705882,0.352941,0.155172

In [ ]:
spaNotDomCLANDF = pd.read_csv('SPA_NotDOM_CLAN_Output.eval.csv')[['File','retracing','repetition']]
spaNotDomCLANDF['File'] = spaNotDomCLANDF['File'].apply(simplifyID)
spaNotDomCLANDF.head()

      File  retracing  repetition
0  BILP007          3          13
1  BILP008          5           4
2  BILP010         14          18
3  BILP011          7           8
4  BILP012         15          26

In [ ]:
spaNotDomFragmentDF = pd.read_csv('Spa_NotDom_Fragment.xls.csv')[['File','Token']]
spaNotDomFragmentDF['File'] = spaNotDomFragmentDF['File'].apply(simplifyID)
#rename token column to part-word repetition
spaNotDomFragmentDF.columns = ['File','part-word repetitions']
spaNotDomFragmentDF.head()

      File  part-word repetitions
0  BILP007                      4
1  BILP008                      1
2  BILP010                      6
3  BILP011                      2
4  BILP012                      7

In [ ]:
#combine catDomLingDF, catDomCLANDF,catDomFragmentDF
spaNotDomDF = spaNotDomLingDF.merge(spaNotDomCLANDF, on='File').merge(spaNotDomFragmentDF, on='File')
#divide retracing, repetition and part-word repetition columns by '# of words' column
spaNotDomDF['retracing'] = spaNotDomDF['retracing'] / spaNotDomDF['# of words']
spaNotDomDF['repetition'] = spaNotDomDF['repetition'] / spaNotDomDF['# of words']
spaNotDomDF['part-word repetitions'] = spaNotDomDF['part-word repetitions'] / spaNotDomDF['# of words']
spaNotDomDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP007,84.0,0.559524,1.285714,0.416667,0.820000,9.333333,0.888889,0.076923,0.035714,0.154762,0.047619
1,BILP008,181.0,0.530387,1.250000,0.425414,0.771429,10.055556,0.777778,0.026882,0.027624,0.022099,0.005525
2,BILP010,97.0,0.608247,1.000000,0.391753,0.594203,5.705882,0.294118,0.118182,0.144330,0.185567,0.061856
3,BILP011,87.0,0.643678,1.818182,0.379310,0.666667,7.909091,0.545455,0.033333,0.080460,0.091954,0.022989
4,BILP012,97.0,0.567010,1.909091,0.309278,0.487179,5.705882,0.352941,0.155172,0.154639,0.268041,0.072165

In [ ]:
spaNotDomDF.shape

(23, 12)

###CatNotDom

In [ ]:
catNotDomLingDF = pd.read_csv('CAT_NotDom_LinguisticFeatures.csv')
catNotDomLingDF = catNotDomLingDF[lingFeatsOfInterest]
catNotDomLingDF['file'] = catNotDomLingDF['file'].apply(simplifyID)
#rename 'file' column to 'File' using .rename
catNotDomLingDF.rename(columns={'file': 'File'}, inplace=True)
print(catNotDomLingDF.shape)

(11, 9)

In [ ]:
catNotDomCLANDF = pd.read_csv('CAT_NotDOM_CLAN_Output.eval.csv')[['File','retracing','repetition']]
catNotDomCLANDF['File'] = catNotDomCLANDF['File'].apply(simplifyID)
catNotDomCLANDF = catNotDomCLANDF[catNotDomCLANDF['File'].isin(list(catNotDomLingDF['File']))]
print(catNotDomCLANDF.shape)

(11, 3)

In [ ]:
catNotDomFragmentDF = pd.read_csv('Cat_NotDom_Fragment.xls.csv', encoding='ISO-8859-1')[['File','Token']]
catNotDomFragmentDF['File'] = catNotDomFragmentDF['File'].apply(simplifyID)
#rename token column to part-word repetition
catNotDomFragmentDF.columns = ['File','part-word repetitions']
catNotDomFragmentDF = catNotDomFragmentDF[catNotDomFragmentDF['File'].isin(list(catNotDomLingDF['File']))]
#spaNotDomFragmentDF = spaNotDomFragmentDF[spaNotDomFragmentDF['File'].isin(list(catNonDomLingDF['File']))]
print(catNotDomFragmentDF.shape)

(11, 2)

In [ ]:
catNonDomDF = catNotDomLingDF.merge(catNotDomCLANDF, on='File').merge(catNotDomFragmentDF, on='File')
#divide retracing, repetition and part-word repetition columns by '# of words' column
catNonDomDF['retracing'] = catNonDomDF['retracing'] / catNonDomDF['# of words']
catNonDomDF['repetition'] = catNonDomDF['repetition'] / catNonDomDF['# of words']
catNonDomDF['part-word repetitions'] = catNonDomDF['part-word repetitions'] / catNonDomDF['# of words']
catNonDomDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP006,206.0,0.432039,1.235294,0.417476,0.811966,7.103448,0.379310,0.024272,0.053398,0.111650,0.019417
1,BILP009,76.0,0.592105,1.066667,0.421053,0.744681,9.500000,0.625000,0.078947,0.000000,0.131579,0.000000
2,BILP013,260.0,0.453846,1.238095,0.438462,0.872340,8.965517,0.517241,0.015385,0.030769,0.042308,0.011538
3,BILP022,266.0,0.439850,0.977778,0.469925,0.785714,12.666667,1.190476,0.030075,0.033835,0.071429,0.067669
4,BILP024,180.0,0.544444,1.064516,0.433333,0.669492,10.000000,0.611111,0.083333,0.077778,0.138889,0.044444

In [ ]:
catNonDomDF.shape

(11, 12)

###Combine

In [ ]:
notDomLingDF = pd.concat([spaNotDomDF, catNonDomDF])
notDomLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP007,84.0,0.559524,1.285714,0.416667,0.820000,9.333333,0.888889,0.076923,0.035714,0.154762,0.047619
1,BILP008,181.0,0.530387,1.250000,0.425414,0.771429,10.055556,0.777778,0.026882,0.027624,0.022099,0.005525
2,BILP010,97.0,0.608247,1.000000,0.391753,0.594203,5.705882,0.294118,0.118182,0.144330,0.185567,0.061856
3,BILP011,87.0,0.643678,1.818182,0.379310,0.666667,7.909091,0.545455,0.033333,0.080460,0.091954,0.022989
4,BILP012,97.0,0.567010,1.909091,0.309278,0.487179,5.705882,0.352941,0.155172,0.154639,0.268041,0.072165

In [ ]:
notDomLingDF.shape

(34, 12)

In [ ]:
print(list(notDomLingDF['File']))

['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019', 'BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018']

In [ ]:
data_X = notDomLingDF.drop(columns=['File'])
data_X.shape

(34, 11)

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [ ]:
notDomLingDF['Class'] = notDomLingDF['File'].apply(getClass)
notDomLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions,Class
0,BILP007,84.0,0.559524,1.285714,0.416667,0.820000,9.333333,0.888889,0.076923,0.035714,0.154762,0.047619,lv
1,BILP008,181.0,0.530387,1.250000,0.425414,0.771429,10.055556,0.777778,0.026882,0.027624,0.022099,0.005525,lv
2,BILP010,97.0,0.608247,1.000000,0.391753,0.594203,5.705882,0.294118,0.118182,0.144330,0.185567,0.061856,lv
3,BILP011,87.0,0.643678,1.818182,0.379310,0.666667,7.909091,0.545455,0.033333,0.080460,0.091954,0.022989,lv
4,BILP012,97.0,0.567010,1.909091,0.309278,0.487179,5.705882,0.352941,0.155172,0.154639,0.268041,0.072165,lv

##Linguistic DL

###SpaDom

In [ ]:
import pandas as pd

In [ ]:
lingFeatsOfInterest = ['file'] + ['# of words', 'Type Token Ratio', 'Noun to Verb ratio', 'Propositional Density','Open Closed Words Ratio',  'Average sentence length', 'Suboordination Main Verb Implied','Proportion Fillers' ]

In [ ]:
def simplifyID(id):
  return id.split('_')[0]

In [ ]:
spaDomLingDF = pd.read_csv('SPA_Dom_LinguisticFeatures.csv')
spaDomLingDF = spaDomLingDF[lingFeatsOfInterest]
spaDomLingDF['file'] = spaDomLingDF['file'].apply(simplifyID)
#rename 'file' column to 'File' using .rename
spaDomLingDF.rename(columns={'file': 'File'}, inplace=True)
spaDomLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers
0,BILP006,402.0,0.315920,0.940000,0.470149,0.640152,8.553191,0.702128,0.069284
1,BILP009,128.0,0.507812,1.166667,0.445312,0.582418,8.000000,0.562500,0.111111
2,BILP013,301.0,0.421927,1.969697,0.425249,0.767442,10.379310,0.551724,0.009868
3,BILP022,141.0,0.503546,1.647059,0.453901,0.627660,14.100000,1.000000,0.078431
4,BILP024,172.0,0.546512,1.160000,0.436047,0.698113,8.600000,0.500000,0.044444

In [ ]:
spaDomCLANDF = pd.read_csv('SPA_DOM_CLAN_Output.eval.csv')[['File','retracing','repetition']]
spaDomCLANDF['File'] = spaDomCLANDF['File'].apply(simplifyID)
spaDomCLANDF.head()

      File  retracing  repetition
0  BILP006         38          38
1  BILP009          8          11
2  BILP013         21          14
3  BILP022          9          15
4  BILP024          9          11

In [ ]:
spaDomFragmentDF = pd.read_csv('Spa_Dom_Fragment.xls.csv')[['File','Token']]
spaDomFragmentDF['File'] = spaDomFragmentDF['File'].apply(simplifyID)
#rename token column to part-word repetition
spaDomFragmentDF.columns = ['File','part-word repetitions']
spaDomFragmentDF.head()

      File  part-word repetitions
0  BILP006                     14
1  BILP009                      3
2  BILP013                      4
3  BILP022                      3
4  BILP024                      7

In [ ]:
#combine catDomLingDF, catDomCLANDF,catDomFragmentDF
spaDomDF = spaDomLingDF.merge(spaDomCLANDF, on='File').merge(spaDomFragmentDF, on='File')
#divide retracing, repetition and part-word repetition columns by '# of words' column
spaDomDF['retracing'] = spaDomDF['retracing'] / spaDomDF['# of words']
spaDomDF['repetition'] = spaDomDF['repetition'] / spaDomDF['# of words']
spaDomDF['part-word repetitions'] = spaDomDF['part-word repetitions'] / spaDomDF['# of words']
spaDomDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP006,402.0,0.315920,0.940000,0.470149,0.640152,8.553191,0.702128,0.069284,0.094527,0.094527,0.034826
1,BILP009,128.0,0.507812,1.166667,0.445312,0.582418,8.000000,0.562500,0.111111,0.062500,0.085938,0.023438
2,BILP013,301.0,0.421927,1.969697,0.425249,0.767442,10.379310,0.551724,0.009868,0.069767,0.046512,0.013289
3,BILP022,141.0,0.503546,1.647059,0.453901,0.627660,14.100000,1.000000,0.078431,0.063830,0.106383,0.021277
4,BILP024,172.0,0.546512,1.160000,0.436047,0.698113,8.600000,0.500000,0.044444,0.052326,0.063953,0.040698

In [ ]:
spaDomDF.shape

(11, 12)

###CatDom

In [ ]:
catDomLingDF = pd.read_csv('CAT_Dom_LinguisticFeatures.csv')
catDomLingDF = catDomLingDF[lingFeatsOfInterest]
catDomLingDF['file'] = catDomLingDF['file'].apply(simplifyID)
#rename 'file' column to 'File' using .rename
catDomLingDF.rename(columns={'file': 'File'}, inplace=True)
print(catDomLingDF.shape)

(23, 9)

In [ ]:
catDomCLANDF = pd.read_csv('SPA_NotDOM_CLAN_Output.eval.csv')[['File','retracing','repetition']]
catDomCLANDF['File'] = catDomCLANDF['File'].apply(simplifyID)
#spaNotDomCLANDF = spaNotDomCLANDF[spaNotDomCLANDF['File'].isin(list(spaNotDomCLANDF['File']))]
print(catDomCLANDF.shape)

(23, 3)

In [ ]:
catDomFragmentDF = pd.read_csv('Spa_NotDom_Fragment.xls.csv')[['File','Token']]
catDomFragmentDF['File'] = catDomFragmentDF['File'].apply(simplifyID)
#rename token column to part-word repetition
catDomFragmentDF.columns = ['File','part-word repetitions']
#spaNotDomFragmentDF = spaNotDomFragmentDF[spaNotDomFragmentDF['File'].isin(list(catNonDomLingDF['File']))]
print(catDomFragmentDF.shape)

(23, 2)

In [ ]:
catDomDF = catDomLingDF.merge(catDomCLANDF, on='File').merge(catDomFragmentDF, on='File')
#divide retracing, repetition and part-word repetition columns by '# of words' column
catDomDF['retracing'] = catDomDF['retracing'] / catDomDF['# of words']
catDomDF['repetition'] = catDomDF['repetition'] / catDomDF['# of words']
catDomDF['part-word repetitions'] = catDomDF['part-word repetitions'] / catDomDF['# of words']
catDomDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP007,110.0,0.572727,1.000000,0.472727,0.750000,11.000000,0.900000,0.081818,0.027273,0.118182,0.036364
1,BILP008,184.0,0.478261,1.166667,0.467391,0.844660,10.823529,0.764706,0.021739,0.027174,0.021739,0.005435
2,BILP010,172.0,0.465116,0.461538,0.534884,0.927083,7.478261,0.521739,0.058140,0.081395,0.104651,0.034884
3,BILP011,77.0,0.584416,2.000000,0.324675,0.860465,7.700000,0.500000,0.038961,0.090909,0.103896,0.025974
4,BILP012,103.0,0.543689,1.285714,0.398058,0.714286,8.583333,0.500000,0.048544,0.145631,0.252427,0.067961

In [ ]:
catDomDF.shape

(23, 12)

###Combine

In [ ]:
domLingDF = pd.concat([spaDomDF, catDomDF])
domLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions
0,BILP006,402.0,0.315920,0.940000,0.470149,0.640152,8.553191,0.702128,0.069284,0.094527,0.094527,0.034826
1,BILP009,128.0,0.507812,1.166667,0.445312,0.582418,8.000000,0.562500,0.111111,0.062500,0.085938,0.023438
2,BILP013,301.0,0.421927,1.969697,0.425249,0.767442,10.379310,0.551724,0.009868,0.069767,0.046512,0.013289
3,BILP022,141.0,0.503546,1.647059,0.453901,0.627660,14.100000,1.000000,0.078431,0.063830,0.106383,0.021277
4,BILP024,172.0,0.546512,1.160000,0.436047,0.698113,8.600000,0.500000,0.044444,0.052326,0.063953,0.040698

In [ ]:
domLingDF.shape

(34, 12)

In [ ]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [ ]:
domLingDF['Class'] = domLingDF['File'].apply(getClass)
domLingDF.head()

,File,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions,Class
0,BILP006,402.0,0.315920,0.940000,0.470149,0.640152,8.553191,0.702128,0.069284,0.094527,0.094527,0.034826,lv
1,BILP009,128.0,0.507812,1.166667,0.445312,0.582418,8.000000,0.562500,0.111111,0.062500,0.085938,0.023438,lv
2,BILP013,301.0,0.421927,1.969697,0.425249,0.767442,10.379310,0.551724,0.009868,0.069767,0.046512,0.013289,lv
3,BILP022,141.0,0.503546,1.647059,0.453901,0.627660,14.100000,1.000000,0.078431,0.063830,0.106383,0.021277,lv
4,BILP024,172.0,0.546512,1.160000,0.436047,0.698113,8.600000,0.500000,0.044444,0.052326,0.063953,0.040698,lv

##Image-text congruence NDL

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
notDominantSpanishImageTextSimDF = pd.read_csv('SPA_NotDom_imageTextCongruenceScores.csv')
#rename Unnamed: 0 column to sample
notDominantSpanishImageTextSimDF = notDominantSpanishImageTextSimDF.rename(columns={'Unnamed: 0': 'Sample'})
notDominantSpanishImageTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,0.269546,0.257789,0.237408,0.266129
1,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,0.257092,0.276224,0.248163,0.266675
2,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,0.231019,0.239711,0.215565,0.235069
3,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,0.319062,0.271305,0.187178,0.300368
4,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,0.287864,0.266844,0.187615,0.290993

In [3]:
notDominantCatalanImageTextSimDF = pd.read_csv('CAT_NotDom_imageTextCongruenceScores.csv')
#rename Unnamed: 0 column to sample
notDominantCatalanImageTextSimDF = notDominantCatalanImageTextSimDF.rename(columns={'Unnamed: 0': 'Sample'})
notDominantCatalanImageTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,0.248080,0.262002,0.215856,0.245906
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,0.316370,0.275753,0.206318,0.282338
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,0.250897,0.251819,0.197365,0.240067
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,0.233117,0.244744,0.195236,0.235246
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,0.245542,0.239898,0.210812,0.235140

In [4]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [5]:
notDominantTextSim_Y = list(notDominantCatalanImageTextSimDF['Sample'].apply(getClass)) + list(notDominantSpanishImageTextSimDF['Sample'].apply(getClass))
notDominantTextSimDF = pd.concat([notDominantCatalanImageTextSimDF, notDominantSpanishImageTextSimDF])
notDominantTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,0.248080,0.262002,0.215856,0.245906
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,0.316370,0.275753,0.206318,0.282338
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,0.250897,0.251819,0.197365,0.240067
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,0.233117,0.244744,0.195236,0.235246
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,0.245542,0.239898,0.210812,0.235140

In [6]:
notDominantTextSimDF['Class'] = notDominantTextSim_Y

In [7]:
notDominantTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",Class
0,BILP006_PreTx_Cat_WABPicnic_Coded.flo.cex,0.248080,0.262002,0.215856,0.245906,lv
1,BILP009_PreTx_Cat_WABPicnic_Coded.flo.cex,0.316370,0.275753,0.206318,0.282338,lv
2,BILP013_PreTx_Cat_WABPicnic_Coded.flo.cex,0.250897,0.251819,0.197365,0.240067,lv
3,BILP022_BACC002_PicnicScene_Cat_Pre_coded.flo.cex,0.233117,0.244744,0.195236,0.235246,lv
4,BILP024_BACC016_PicnicScene_Cat_Pre_20240123_C...,0.245542,0.239898,0.210812,0.235140,lv

In [8]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [9]:
def simplifyID(id):
  return id.split('_')[0]

In [10]:
notDominantTextSimDF['Sample'] = notDominantTextSimDF['Sample'].apply(simplifyID)

In [11]:
notDominantTextSimDF

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",Class
0,BILP006,0.248080,0.262002,0.215856,0.245906,lv
1,BILP009,0.316370,0.275753,0.206318,0.282338,lv
2,BILP013,0.250897,0.251819,0.197365,0.240067,lv
3,BILP022,0.233117,0.244744,0.195236,0.235246,lv
4,BILP024,0.245542,0.239898,0.210812,0.235140,lv
5,BILP026,0.168733,0.238150,0.220993,0.209316,lv
6,BISE004,0.335320,0.290025,0.202591,0.308057,nfv
7,BISE005,0.335940,0.258200,0.189844,0.311178,nfv
8,BISE013,0.320707,0.288989,0.184911,0.290291,nfv
9,BISE016,0.344719,0.314872,0.224985,0.303892,nfv
10,BISE018,0.340901,0.306623,0.194797,0.306714,nfv
0,BILP007,0.269546,0.257789,0.237408,0.266129,lv
1,BILP008,0.257092,0.276224,0.248163,0.266675,lv
2,BILP010,0.231019,0.239711,0.215565,0.235069,lv
3,BILP011,0.319062,0.271305,0.187178,0.300368,lv
4,BILP012,0.287864,0.266844,0.187615,0.290993,lv
5,BILP014,0.252157,0.235786,0.217997,0.240026,lv
6,BILP015,0.267906,0.256235,0.212523,0.236923,lv
7,BILP017,0.241193,0.242708,0.200745,0.235849,lv
8,BILP018,0.171136,0.229548,0.192635,0.196519,lv
9,BILP019,0.184501,0.232708,0.234522,0.214700,lv
10,BILP020,0.267172,0.248045,0.230409,0.259891,lv
11,BILP021,0.309475,0.280515,0.191910,0.297703,lv
12,BILP025,0.269737,0.253329,0.180959,0.241922,lv
13,BILP027,0.266783,0.240755,0.225484,0.263407,lv
14,BILP028,0.240974,0.234566,0.199961,0.213769,lv
15,BILP029,0.225410,0.256671,0.214377,0.226821,lv
16,BIOBS003,0.222505,0.236055,0.217469,0.191461,lv
17,BIOBS004,0.106418,0.202871,0.195401,0.158835,nfv
18,BIOBS005,0.360937,0.291265,0.201566,0.312351,lv
19,BISE010,0.362460,0.316364,0.175036,0.341660,nfv
20,BISE011,0.346080,0.290710,0.187590,0.308032,nfv
21,BISE014,0.341816,0.262065,0.218837,0.298481,nfv
22,BISE019,0.350423,0.303022,0.192894,0.318857,nfv

##Image-text congruence DL

In [12]:
import os
import pandas as pd
import numpy as nps
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
dominantSpanishImageTextSimDF = pd.read_csv('SPA_Dom_imageTextCongruenceScores.csv')
#rename Unnamed: 0 column to sample
dominantSpanishImageTextSimDF = dominantSpanishImageTextSimDF.rename(columns={'Unnamed: 0': 'Sample'})
dominantSpanishImageTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,0.252843,0.267068,0.180211,0.256789
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,0.255348,0.257218,0.235588,0.244238
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,0.270008,0.254352,0.187814,0.240139
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,0.247419,0.254995,0.212980,0.225332
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,0.264987,0.243122,0.185527,0.232036

In [14]:
dominantCatalanImageTextSimDF = pd.read_csv('CAT_Dom_imageTextCongruenceScores.csv')
#rename Unnamed: 0 column to sample
dominantCatalanImageTextSimDF = dominantCatalanImageTextSimDF.rename(columns={'Unnamed: 0': 'Sample'})
dominantCatalanImageTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP007_Cat_PicnicScene_Post_coded.flo.cex,0.263748,0.254969,0.192145,0.256237
1,BILP008_PreTx_Cat_WABPicnic_Coded.flo.cex,0.329465,0.282022,0.171836,0.293588
2,BILP010_PreTx_Cat_WABPicnic_Coded.flo.cex,0.159932,0.218802,0.223910,0.197884
3,BILP011_PicnicScene_Cat_Pre_Coded.flo.cex,0.325117,0.299401,0.204469,0.311126
4,BILP012_PreTx_Cat_WABPicnic_Coded.flo.cex,0.321507,0.272960,0.208914,0.272938

In [15]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [16]:
dominantTextSim_Y = list(dominantCatalanImageTextSimDF['Sample'].apply(getClass)) + list(dominantSpanishImageTextSimDF['Sample'].apply(getClass))
dominantTextSimDF = pd.concat([dominantCatalanImageTextSimDF, dominantSpanishImageTextSimDF])
dominantTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP007_Cat_PicnicScene_Post_coded.flo.cex,0.263748,0.254969,0.192145,0.256237
1,BILP008_PreTx_Cat_WABPicnic_Coded.flo.cex,0.329465,0.282022,0.171836,0.293588
2,BILP010_PreTx_Cat_WABPicnic_Coded.flo.cex,0.159932,0.218802,0.223910,0.197884
3,BILP011_PicnicScene_Cat_Pre_Coded.flo.cex,0.325117,0.299401,0.204469,0.311126
4,BILP012_PreTx_Cat_WABPicnic_Coded.flo.cex,0.321507,0.272960,0.208914,0.272938

In [17]:
def simplify(id):
  return id.split('_')[0]

In [18]:
dominantTextSimDF['Sample'] = dominantTextSimDF['Sample'].apply(simplify)

In [19]:
dominantTextSimDF.head()

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP007,0.263748,0.254969,0.192145,0.256237
1,BILP008,0.329465,0.282022,0.171836,0.293588
2,BILP010,0.159932,0.218802,0.223910,0.197884
3,BILP011,0.325117,0.299401,0.204469,0.311126
4,BILP012,0.321507,0.272960,0.208914,0.272938

In [20]:
dominantTextSimDF['Class'] = dominantTextSim_Y

#Compare ling NDL vs ling DL

In [ ]:
domLingDF.shape

(34, 13)

In [ ]:
notDomLingDF.shape

(34, 13)

In [ ]:
notDomLingDF.rename(columns={'File': 'Sample_ID'}, inplace=True)

In [ ]:
notDomLingDF.columns

Index(['File', '# of words', 'Type Token Ratio', 'Noun to Verb ratio',
       'Propositional Density', 'Open Closed Words Ratio',
       'Average sentence length', 'Suboordination Main Verb Implied',
       'Proportion Fillers', 'retracing', 'repetition',
       'part-word repetitions', 'Class'],
      dtype='object')

In [ ]:
print(list(domLingDF['Sample_ID']))
print(list(notDomLingDF['Sample_ID']))

['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018', 'BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019']
['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019', 'BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018']

In [ ]:
nfvNotDomLingDF = notDomLingDF[notDomLingDF['Class'] == 'nfv']
lvNotDomLingDF = notDomLingDF[notDomLingDF['Class'] == 'lv']

In [ ]:
lvDomLingDF = domLingDF[domLingDF['Class'] == 'lv']
nfvDomLingDF = domLingDF[domLingDF['Class'] == 'nfv']
#

In [31]:
import scipy.stats as stats
from scipy.stats import pearsonr

In [ ]:
lvNotDomLingDF

,Sample_ID,# of words,Type Token Ratio,Noun to Verb ratio,Propositional Density,Open Closed Words Ratio,Average sentence length,Suboordination Main Verb Implied,Proportion Fillers,retracing,repetition,part-word repetitions,Class
0,BILP007,84.0,0.559524,1.285714,0.416667,0.820000,9.333333,0.888889,0.076923,0.035714,0.154762,0.047619,lv
1,BILP008,181.0,0.530387,1.250000,0.425414,0.771429,10.055556,0.777778,0.026882,0.027624,0.022099,0.005525,lv
2,BILP010,97.0,0.608247,1.000000,0.391753,0.594203,5.705882,0.294118,0.118182,0.144330,0.185567,0.061856,lv
3,BILP011,87.0,0.643678,1.818182,0.379310,0.666667,7.909091,0.545455,0.033333,0.080460,0.091954,0.022989,lv
4,BILP012,97.0,0.567010,1.909091,0.309278,0.487179,5.705882,0.352941,0.155172,0.154639,0.268041,0.072165,lv
5,BILP014,99.0,0.626263,0.850000,0.535354,0.836364,12.375000,0.875000,0.019802,0.070707,0.020202,0.020202,lv
6,BILP015,79.0,0.620253,2.111111,0.430380,0.679245,9.875000,0.250000,0.112360,0.025316,0.101266,0.012658,lv
7,BILP017,145.0,0.586207,1.476190,0.434483,0.850000,13.181818,0.818182,0.020270,0.041379,0.013793,0.034483,lv
8,BILP018,247.0,0.445344,1.135135,0.518219,0.748344,9.500000,1.076923,0.064394,0.044534,0.028340,0.024291,lv
9,BILP019,127.0,0.496063,0.789474,0.472441,0.584270,6.350000,0.400000,0.092199,0.110236,0.062992,0.023622,lv
10,BILP020,103.0,0.592233,1.923077,0.388350,0.750000,6.866667,0.266667,0.134454,0.106796,0.058252,0.019417,lv
11,BILP021,107.0,0.532710,1.500000,0.373832,0.602564,8.230769,0.461538,0.144000,0.084112,0.102804,0.037383,lv
12,BILP025,334.0,0.449102,2.085714,0.431138,0.728643,10.774194,0.677419,0.029070,0.032934,0.059880,0.008982,lv
13,BILP027,206.0,0.441748,1.185185,0.461165,0.487805,10.842105,0.684211,0.155738,0.145631,0.266990,0.058252,lv
14,BILP028,307.0,0.495114,0.821429,0.540717,0.855491,11.807692,1.038462,0.043614,0.117264,0.026059,0.026059,lv
15,BILP029,60.0,0.650000,1.571429,0.400000,0.684211,7.500000,0.250000,0.062500,0.150000,0.066667,0.050000,lv
16,BIOBS003,103.0,0.679612,1.181818,0.407767,0.688525,6.866667,0.200000,0.000000,0.067961,0.087379,0.009709,lv
18,BIOBS005,118.0,0.567797,2.833333,0.347458,0.808824,13.111111,0.444444,0.040650,0.000000,0.025424,0.033898,lv
0,BILP006,206.0,0.432039,1.235294,0.417476,0.811966,7.103448,0.379310,0.024272,0.053398,0.111650,0.019417,lv
1,BILP009,76.0,0.592105,1.066667,0.421053,0.744681,9.500000,0.625000,0.078947,0.000000,0.131579,0.000000,lv
2,BILP013,260.0,0.453846,1.238095,0.438462,0.872340,8.965517,0.517241,0.015385,0.030769,0.042308,0.011538,lv
3,BILP022,266.0,0.439850,0.977778,0.469925,0.785714,12.666667,1.190476,0.030075,0.033835,0.071429,0.067669,lv
4,BILP024,180.0,0.544444,1.064516,0.433333,0.669492,10.000000,0.611111,0.083333,0.077778,0.138889,0.044444,lv
5,BILP026,132.0,0.424242,0.761905,0.545455,0.873239,9.428571,0.642857,0.007576,0.030303,0.083333,0.000000,lv

In [ ]:
import pandas as pd

# Example: assume your DataFrame is called df
means = temp_data_X.mean(numeric_only=True)
stds = temp_data_X.std(numeric_only=True)
mins = temp_data_X.min(numeric_only=True)
maxs = temp_data_X.max(numeric_only=True)

# Combine into a single summary table
summary = pd.DataFrame({
    'Mean': means,
    'Standard Deviation': stds,
    'Min': mins,
    'Max': maxs
})

print(summary)

In [ ]:
def statsSummary(df):
  means = df.mean(numeric_only=True)
  stds = df.std(numeric_only=True)
  mins = df.min(numeric_only=True)
  maxs = df.max(numeric_only=True)
  summary = pd.DataFrame({
    'Mean': means,
    'Standard Deviation': stds,
    'Min': mins,
    'Max': maxs
  })
  return summary

In [29]:
def domNonDomComparison(domDF, nonDomDF):
  normallyDistributedFeats = []
  notNormallyDistributedFeats = []
  featurePValues = {}
  for feature in domDF.columns:
    #output mean, sd, min, max,

  #use Shapiro-Wilk test to see if distribution of variables in both groups is normal
    if feature in ['Sample_ID', 'Class']:
      continue
    _,p_dom = stats.shapiro(domDF[feature])
    _,p_nonDom = stats.shapiro(nonDomDF[feature])
    # if both distribution are normal, use t-test
    if p_dom > 0.05 and p_nonDom > 0.05:
      t_stat, p_feature = stats.ttest_ind(domDF[feature], nonDomDF[feature])
      featurePValues[feature] = float(p_feature)
      normallyDistributedFeats.append(feature)
    else: #if either distribution wasn't normal, use mannwhitney u test
      t_stat, p_feature = stats.mannwhitneyu(domDF[feature], nonDomDF[feature])
      featurePValues[feature] = float(p_feature)
      notNormallyDistributedFeats.append(feature)
    from statsmodels.stats.multitest import fdrcorrection

# 2. Apply FDR correction
  all_features = list(featurePValues.keys())
  raw_pvals = [featurePValues[feat] for feat in all_features]
  rejected, fdr_corrected_pvals = fdrcorrection(raw_pvals)

  # 3. Create corrected p-value dictionary
  featureFDRPValues = dict(zip(all_features, fdr_corrected_pvals))
  featureFDRPValues = {k: v.item() for k, v in featureFDRPValues.items()}
  print(featureFDRPValues)
  significantFeatures = {k: v for k, v in featureFDRPValues.items() if v < 0.05}
  print("Significant features:", significantFeatures)

In [ ]:
lvNotDomLingDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
# of words,154.208333,79.265091,60.000000,97.000000,122.500000,206.000000,334.000000
Type Token Ratio,0.540742,0.079077,0.424242,0.452660,0.551984,0.596237,0.679612
Noun to Verb ratio,1.377964,0.510899,0.761905,1.048387,1.236695,1.633117,2.833333
Propositional Density,0.432893,0.059300,0.309278,0.397938,0.427897,0.463355,0.545455
Open Closed Words Ratio,0.725050,0.113456,0.487179,0.668785,0.746513,0.813974,0.873239
Average sentence length,9.318957,2.287377,5.705882,7.400862,9.464286,10.791171,13.181818
Suboordination Main Verb Implied,0.594501,0.282397,0.200000,0.372718,0.578283,0.787879,1.190476
Proportion Fillers,0.065380,0.049176,0.000000,0.026229,0.053057,0.097239,0.155738
retracing,0.069405,0.047862,0.000000,0.032393,0.060680,0.107656,0.154639
repetition,0.092569,0.070491,0.013793,0.038816,0.077381,0.116633,0.268041
part-word repetitions,0.029674,0.021232,0.000000,0.012378,0.023957,0.045238,0.072165

In [ ]:
lvDomLingDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
# of words,183.333333,108.443801,73.000000,108.250000,151.000000,203.250000,508.000000
Type Token Ratio,0.506870,0.078093,0.315920,0.474975,0.516406,0.557311,0.684932
Noun to Verb ratio,1.090995,0.399935,0.461538,0.825820,0.989130,1.196429,2.000000
Propositional Density,0.462748,0.045297,0.324675,0.449743,0.467029,0.484977,0.536398
Open Closed Words Ratio,0.784927,0.112697,0.573770,0.738431,0.778165,0.856783,0.985185
Average sentence length,9.892889,2.170922,7.076923,8.440909,9.429167,10.844920,14.947368
Suboordination Main Verb Implied,0.689050,0.273281,0.315789,0.500000,0.625874,0.813578,1.578947
Proportion Fillers,0.048447,0.027288,0.009868,0.029786,0.043349,0.068691,0.111111
retracing,0.073968,0.048168,0.000000,0.038223,0.066799,0.097304,0.191781
repetition,0.075614,0.057192,0.011905,0.034801,0.064585,0.104085,0.252427
part-word repetitions,0.027546,0.015753,0.005435,0.013256,0.025182,0.036888,0.067961

In [ ]:
domNonDomComparison(lvNotDomLingDF, lvDomLingDF)

{'# of words': 0.5750242391083787, 'Type Token Ratio': 0.3911590809568262, 'Noun to Verb ratio': 0.2679444512082177, 'Propositional Density': 0.2679444512082177, 'Open Closed Words Ratio': 0.2679444512082177, 'Average sentence length': 0.5750242391083787, 'Suboordination Main Verb Implied': 0.536410087958864, 'Proportion Fillers': 0.5750242391083787, 'retracing': 0.7435233371260561, 'repetition': 0.5750242391083787, 'part-word repetitions': 0.7435233371260561}
{}

In [ ]:
nfvNotDomLingDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
# of words,90.400000,54.663008,42.000000,61.750000,77.000000,86.000000,235.000000
Type Token Ratio,0.565504,0.065764,0.428571,0.524230,0.576694,0.614752,0.642857
Noun to Verb ratio,2.026190,0.741761,0.944444,1.517857,1.750000,2.753968,3.000000
Propositional Density,0.366242,0.056599,0.267857,0.320959,0.378748,0.412089,0.430233
Open Closed Words Ratio,0.741588,0.136217,0.607843,0.658622,0.716880,0.785329,1.074074
Average sentence length,8.937512,4.432511,4.307692,7.025568,8.188889,8.650000,19.583333
Suboordination Main Verb Implied,0.375808,0.300036,0.000000,0.229167,0.316667,0.390909,1.000000
Proportion Fillers,0.066730,0.047511,0.000000,0.037490,0.056505,0.099524,0.151163
retracing,0.029185,0.031562,0.000000,0.002155,0.022763,0.046972,0.095238
repetition,0.115869,0.166821,0.000000,0.044963,0.053975,0.115941,0.571429
part-word repetitions,0.042384,0.044613,0.000000,0.013812,0.025978,0.051786,0.142857

In [ ]:
nfvDomLingDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
# of words,103.600000,90.436227,25.000000,70.750000,82.500000,96.250000,350.000000
Type Token Ratio,0.581843,0.128162,0.340206,0.519965,0.585772,0.662500,0.800000
Noun to Verb ratio,1.522750,0.634629,0.666667,1.158863,1.426471,1.597902,2.833333
Propositional Density,0.390394,0.087231,0.244444,0.341597,0.409402,0.454103,0.520000
Open Closed Words Ratio,0.833319,0.169889,0.553846,0.722619,0.814103,0.983824,1.057692
Average sentence length,7.429324,2.585938,5.000000,6.153409,6.566667,6.991071,13.000000
Suboordination Main Verb Implied,0.259595,0.287706,0.000000,0.074405,0.166667,0.318182,0.888889
Proportion Fillers,0.048690,0.061900,0.000000,0.007143,0.033605,0.051156,0.207921
retracing,0.046404,0.040535,0.000000,0.023992,0.034904,0.069457,0.120000
repetition,0.090225,0.091539,0.000000,0.035756,0.055523,0.135385,0.247423
part-word repetitions,0.034271,0.028741,0.000000,0.013845,0.029388,0.046405,0.094017

In [ ]:
domNonDomComparison(nfvNotDomLingDF, nfvDomLingDF)

{'# of words': 0.8701325350279931, 'Type Token Ratio': 0.8701325350279931, 'Noun to Verb ratio': 0.5558557875083343, 'Propositional Density': 0.7418812102551643, 'Open Closed Words Ratio': 0.5558557875083343, 'Average sentence length': 0.5558557875083343, 'Suboordination Main Verb Implied': 0.5558557875083343, 'Proportion Fillers': 0.5558557875083343, 'retracing': 0.5558557875083343, 'repetition': 0.8701325350279931, 'part-word repetitions': 0.9397203669477441}
{}

#Compare word param NDL vs DL

In [ ]:
domWordParamsDF.shape

(34, 10)

In [ ]:
nfvDomWordParamsDF = domWordParamsDF[domWordParamsDF['Class'] == 'nfv']
lvDomWordParamsDF = domWordParamsDF[domWordParamsDF['Class'] == 'lv']

In [ ]:
nfvNotDomWordParamsDF = notDomWordParamsDF[notDomWordParamsDF['Class'] == 'nfv']
lvNotDomWordParamsDF = notDomWordParamsDF[notDomWordParamsDF['Class'] == 'lv']

In [ ]:
domNonDomComparison(nfvNotDomWordParamsDF, nfvDomWordParamsDF)

{'Frequency per million average': 1.0, 'Verb Frequency per million average': 1.0, 'Noun Frequency per million average': 1.0, '% high frequency verbs': 1.0, 'Word length by syllables average': 1.0, 'Concreteness average': 1.0, 'Age of Acquisition min average': 1.0, 'Word length by phonemes average': 1.0}
Significant features: {}

In [ ]:
nfvNotDomWordParamsDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Frequency per million average,9013.502029,1649.514010,6987.748970,7797.767344,8672.185125,10316.085498,11725.807729
Verb Frequency per million average,1527.226140,1705.991930,34.552418,202.073821,353.276257,3216.017736,3877.290700
Noun Frequency per million average,190.730725,78.193718,93.253931,122.959159,175.561151,259.241918,306.267412
% high frequency verbs,0.356898,0.122789,0.142857,0.293831,0.366667,0.444444,0.500000
Word length by syllables average,1.670306,0.117079,1.527778,1.551339,1.687791,1.766682,1.811594
Concreteness average,3.118199,0.078524,3.000528,3.071775,3.129470,3.162505,3.267438
Age of Acquisition min average,2.227696,1.204831,1.037037,1.111667,1.978219,3.293182,4.000000
Word length by phonemes average,3.473397,0.364127,2.860465,3.275194,3.500000,3.716676,4.063830

In [ ]:
nfvDomWordParamsDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Frequency per million average,9440.652998,2537.930796,6017.525765,7656.368555,8953.659220,11837.101153,12736.603697
Verb Frequency per million average,1670.879243,1832.141016,7.854285,105.153719,1043.008833,3218.571016,4786.561625
Noun Frequency per million average,215.958434,118.073708,41.065113,160.591791,222.438385,265.664418,470.684813
% high frequency verbs,0.378833,0.193619,0.000000,0.340909,0.378655,0.463211,0.666667
Word length by syllables average,1.672683,0.150177,1.393617,1.579513,1.727833,1.776339,1.880000
Concreteness average,3.093406,0.095717,2.937116,3.053981,3.075202,3.132473,3.289445
Age of Acquisition min average,2.205928,1.142782,1.047619,1.131219,2.082955,3.222403,3.700000
Word length by phonemes average,3.499141,0.501596,2.577320,3.141889,3.580974,3.792857,4.240000

In [ ]:
domNonDomComparison(lvNotDomWordParamsDF, lvDomWordParamsDF)

{'Frequency per million average': 0.013827651979299187, 'Verb Frequency per million average': 0.0013875333819154, 'Noun Frequency per million average': 0.0013875333819154, '% high frequency verbs': 0.05796105555796801, 'Word length by syllables average': 0.010655890500736466, 'Concreteness average': 0.05796105555796801, 'Age of Acquisition min average': 0.004755482937532943, 'Word length by phonemes average': 0.010413290012164587}
Significant features: {'Frequency per million average': 0.013827651979299187, 'Verb Frequency per million average': 0.0013875333819154, 'Noun Frequency per million average': 0.0013875333819154, 'Word length by syllables average': 0.010655890500736466, 'Age of Acquisition min average': 0.004755482937532943, 'Word length by phonemes average': 0.010413290012164587}

In [ ]:
lvNotDomWordParamsDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Frequency per million average,9403.876932,1417.658149,6548.642302,8460.684355,9197.264288,10378.879364,12287.391631
Verb Frequency per million average,874.933489,1258.331301,38.193465,162.309917,243.306959,757.086842,4418.687848
Noun Frequency per million average,199.134826,69.536328,84.727072,143.857139,183.730903,231.690261,355.917184
% high frequency verbs,0.427765,0.155820,0.000000,0.328947,0.451190,0.505952,0.692308
Word length by syllables average,1.646589,0.107070,1.402985,1.581918,1.671318,1.729741,1.798611
Concreteness average,3.001198,0.060385,2.862349,2.963438,2.998774,3.042043,3.112717
Age of Acquisition min average,1.608231,0.908252,1.017857,1.097059,1.138916,1.515476,3.789474
Word length by phonemes average,3.488719,0.334596,2.765152,3.257904,3.612409,3.716357,3.979167

In [ ]:
lvDomWordParamsDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Frequency per million average,8309.271564,1419.595266,6211.369971,7448.556738,8072.503928,9033.622919,10947.149415
Verb Frequency per million average,2435.818134,1394.902892,160.826300,1532.183736,2819.128935,3432.786972,4399.578235
Noun Frequency per million average,290.883646,88.515595,95.405180,242.427392,316.113573,356.288658,426.677611
% high frequency verbs,0.507727,0.122888,0.300000,0.428571,0.494565,0.586207,0.777778
Word length by syllables average,1.566916,0.086004,1.390805,1.507867,1.582456,1.620143,1.784884
Concreteness average,2.967431,0.059924,2.851883,2.913037,2.963461,3.014708,3.101160
Age of Acquisition min average,2.682999,1.024433,1.086957,2.038603,3.035714,3.392361,4.172414
Word length by phonemes average,3.253589,0.220537,2.731959,3.135510,3.251866,3.366477,3.726744

In [ ]:
domWordParamsDF.head()

,Sample_ID,Frequency per million average,Verb Frequency per million average,Noun Frequency per million average,% high frequency verbs,Word length by syllables average,Concreteness average,Age of Acquisition min average,Word length by phonemes average,Phonotactic Probability Unigram Mean,Phonotactic Probability Bigram Mean,Class
0,BILP006,10089.657314,160.826300,177.565780,0.300000,1.549751,2.893011,1.101266,3.253731,1.223483,1.019752,lv
1,BILP009,10232.391784,405.579276,95.405180,0.388889,1.609375,3.020125,1.102362,3.390625,1.205589,1.017614,lv
2,BILP013,10693.611268,213.673143,201.699784,0.363636,1.676667,3.034649,1.103448,3.600000,1.245204,1.024621,lv
3,BILP022,10947.149415,185.186031,206.776077,0.411765,1.637681,3.034450,1.154412,3.572464,1.255858,1.024531,lv
4,BILP024,10649.942109,281.570663,150.461315,0.440000,1.784884,2.981626,1.145455,3.726744,1.235113,1.022066,lv

#Compare speech-timing NDL vs DL

In [ ]:
notDomAcousticDF['Class'] = notDomAcousticY

In [ ]:
domAcousticDF['Class'] = domAcousticY

In [ ]:
lvNotDomAcousticDF = notDomAcousticDF[notDomAcousticDF['Class'] == 'lv']
nfvNotDomAcousticDF = notDomAcousticDF[notDomAcousticDF['Class'] == 'nfv']

In [ ]:
lvDomAcousticDF = domAcousticDF[domAcousticDF['Class'] == 'lv']
nfvDomAcousticDF = domAcousticDF[domAcousticDF['Class'] == 'nfv']

In [ ]:
lvNotDomAcousticDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Mean Pause Duration,1.010591,0.359972,0.411429,0.748284,0.959532,1.154729,1.805333
Variability of Pause Duration,0.685416,0.709025,0.005319,0.188767,0.454397,0.832212,2.997763
speechrate,2.623347,0.643777,1.405752,2.188876,2.623750,3.014515,4.005635
Average Syllable Duration,0.240235,0.026099,0.202889,0.224591,0.237443,0.255303,0.315347
Articulation rate,4.206879,0.429799,3.171115,3.917038,4.211725,4.452650,4.928815
Speech-to-pause ratio,2.811716,4.848994,0.509389,1.156130,1.578271,2.415347,25.090199
# of pauses,51.041667,27.461402,8.000000,30.750000,42.500000,68.250000,101.000000
# words/min,72.995315,26.494853,36.201234,52.828079,67.262527,89.498169,140.780559
# propositions/min,32.196552,13.573447,11.196258,21.720978,29.271804,42.273899,59.890072

In [ ]:
lvDomAcousticDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Mean Pause Duration,1.022778,0.419532,0.320000,0.720116,0.935211,1.252119,1.766800
Variability of Pause Duration,0.700446,0.711996,0.000000,0.163143,0.359664,1.150234,2.344119
speechrate,2.747628,0.702909,1.643254,2.173900,2.577180,3.386326,3.911343
Average Syllable Duration,0.237078,0.028002,0.195858,0.222215,0.230073,0.248186,0.290022
Articulation rate,4.272449,0.484687,3.448017,4.029364,4.346475,4.500225,5.105736
Speech-to-pause ratio,11.242717,44.104567,0.730616,1.070195,1.631750,2.932373,218.138322
# of pauses,49.250000,36.965613,2.000000,22.750000,39.500000,61.000000,155.000000
# words/min,92.933208,38.852546,52.280726,62.800658,80.439748,108.137652,206.098239
# propositions/min,43.389959,19.276321,19.845470,29.099032,39.010008,51.887584,97.508844

In [ ]:
domNonDomComparison(lvNotDomAcousticDF, lvDomAcousticDF)

{'Mean Pause Duration': 0.9144680757084211, 'Variability of Pause Duration': 0.9141289197353917, 'speechrate': 0.8840864304147975, 'Average Syllable Duration': 0.8840864304147975, 'Articulation rate': 0.8840864304147975, 'Speech-to-pause ratio': 0.8840864304147975, '# of pauses': 0.8840864304147975, '# words/min': 0.2541574783522484, '# propositions/min': 0.2541574783522484}
Significant features: {}

In [ ]:
nfvNotDomAcousticDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Mean Pause Duration,1.153993,0.554127,0.694261,0.795554,0.960859,1.395077,2.489500
Variability of Pause Duration,0.897491,0.875700,0.070806,0.245848,0.643970,1.421552,2.804910
speechrate,1.995854,0.358366,1.603646,1.675925,1.934138,2.229713,2.645089
Average Syllable Duration,0.295341,0.055418,0.213411,0.260084,0.283898,0.320918,0.406543
Articulation rate,3.489851,0.629945,2.459767,3.117202,3.524212,3.844920,4.685802
Speech-to-pause ratio,1.650440,0.973338,0.554529,1.088911,1.480077,1.926143,4.022653
# of pauses,42.500000,22.167293,14.000000,26.000000,39.000000,53.750000,89.000000
# words/min,54.525970,28.692804,27.219784,39.916480,50.102652,52.401561,129.349625
# propositions/min,20.335107,12.507272,9.725477,13.115938,17.349635,20.567682,52.642289

In [ ]:
nfvDomAcousticDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
Mean Pause Duration,0.904726,0.403011,0.328000,0.701333,0.866444,1.120267,1.724406
Variability of Pause Duration,0.398032,0.399914,0.000576,0.109564,0.294810,0.464351,1.152011
speechrate,2.284112,0.531958,1.641919,1.777930,2.422730,2.518031,3.162991
Average Syllable Duration,0.292360,0.048945,0.216261,0.259949,0.289772,0.326671,0.376641
Articulation rate,3.509374,0.598938,2.655048,3.062947,3.451050,3.847631,4.624048
Speech-to-pause ratio,13.870750,33.906230,0.687459,1.267305,1.588318,2.483900,109.365577
# of pauses,32.600000,24.775436,3.000000,16.000000,29.500000,37.000000,86.000000
# words/min,67.939010,31.259376,21.416334,52.961842,61.994575,78.859011,140.871422
# propositions/min,26.462061,12.697856,8.566533,17.430031,25.363680,34.613745,48.298773

In [ ]:
domNonDomComparison(nfvNotDomAcousticDF, nfvDomAcousticDF)

{'Mean Pause Duration': 0.46133245941257883, 'Variability of Pause Duration': 0.46133245941257883, 'speechrate': 0.46133245941257883, 'Average Syllable Duration': 0.9441625772089128, 'Articulation rate': 0.9441625772089128, 'Speech-to-pause ratio': 0.46133245941257883, '# of pauses': 0.46133245941257883, '# words/min': 0.46133245941257883, '# propositions/min': 0.46133245941257883}
Significant features: {}

#Combine image-text congruence NDL vs DL

In [34]:
notDominantImageTextSimDF = notDominantTextSimDF

In [35]:
dominantImageTextSimDF = dominantTextSimDF

In [36]:
notDominantImageTextSimDF.rename(columns={'Sample': 'Sample_ID'}, inplace=True)

In [37]:
nfvNotDomImageTextSimDF = notDominantImageTextSimDF[notDominantImageTextSimDF['Class'] == 'nfv']
lvNotDomImageTextSimDF = notDominantImageTextSimDF[notDominantImageTextSimDF['Class'] == 'lv']

In [38]:
nfvDomImageTextSimDF = dominantImageTextSimDF[dominantImageTextSimDF['Class'] == 'nfv']
lvDomImageTextSimDF = dominantImageTextSimDF[dominantImageTextSimDF['Class'] == 'lv']

In [39]:
nfvNotDomImageTextSimDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')",0.318478,0.075289,0.106418,0.335475,0.341359,0.345740,0.362460
"('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')",0.283374,0.034489,0.202871,0.268796,0.290368,0.305723,0.316364
"('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')",0.196689,0.015213,0.175036,0.188153,0.193845,0.200794,0.224985
"('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",0.294600,0.049596,0.158835,0.299834,0.307373,0.310398,0.341660

In [40]:
nfvDomImageTextSimDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')",0.307849,0.061626,0.149369,0.292450,0.321716,0.346156,0.358015
"('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')",0.275953,0.030156,0.216096,0.264318,0.270715,0.301070,0.312632
"('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')",0.194858,0.016274,0.166332,0.187523,0.191710,0.203504,0.224601
"('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",0.278320,0.045409,0.175161,0.259599,0.295934,0.307052,0.322320

In [41]:
domNonDomComparison(nfvNotDomImageTextSimDF, nfvDomImageTextSimDF)

{"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')": 0.7979624020353986, "('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')": 0.7979624020353986, "('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')": 0.7979624020353986, "('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')": 0.7979624020353986}
Significant features: {}

In [42]:
lvNotDomImageTextSimDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')",0.254467,0.045205,0.168733,0.232592,0.251527,0.269594,0.360937
"('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')",0.252601,0.017110,0.229548,0.239321,0.249932,0.263212,0.291265
"('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')",0.210128,0.017370,0.180959,0.196833,0.211668,0.218746,0.248163
"('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",0.247441,0.032595,0.191461,0.233007,0.240046,0.266266,0.312351

In [43]:
lvDomImageTextSimDF.describe().T.drop(columns='count')

,mean,std,min,25%,50%,75%,max
"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')",0.257570,0.054322,0.129812,0.234007,0.261629,0.300205,0.330297
"('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')",0.254352,0.022837,0.208578,0.241847,0.254982,0.267097,0.306874
"('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')",0.197403,0.017305,0.171836,0.182857,0.194801,0.209931,0.235588
"('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",0.244055,0.040543,0.134419,0.225367,0.242189,0.270943,0.313451

In [44]:
domNonDomComparison(lvNotDomImageTextSimDF, lvDomImageTextSimDF)

{"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')": 0.8306274845856082, "('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')": 0.8306274845856082, "('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')": 0.05776616774750283, "('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')": 0.8306274845856082}
Significant features: {}

In [45]:
dominantTextSimDF

,Sample,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')",Class
0,BILP007,0.263748,0.254969,0.192145,0.256237,lv
1,BILP008,0.329465,0.282022,0.171836,0.293588,lv
2,BILP010,0.159932,0.218802,0.223910,0.197884,lv
3,BILP011,0.325117,0.299401,0.204469,0.311126,lv
4,BILP012,0.321507,0.272960,0.208914,0.272938,lv
5,BILP014,0.330297,0.259062,0.199364,0.270278,lv
6,BILP015,0.258683,0.258453,0.197457,0.245229,lv
7,BILP017,0.265078,0.259104,0.177313,0.239133,lv
8,BILP018,0.296294,0.268597,0.199221,0.274814,lv
9,BILP019,0.187633,0.234738,0.220124,0.220139,lv
10,BILP020,0.231284,0.243609,0.191381,0.259724,lv
11,BILP021,0.234914,0.238025,0.191370,0.225378,lv
12,BILP025,0.263537,0.245800,0.173680,0.226289,lv
13,BILP027,0.225384,0.246912,0.183121,0.225813,lv
14,BILP028,0.259721,0.236453,0.182067,0.215836,lv
15,BILP029,0.311939,0.267182,0.220771,0.292539,lv
16,BIOBS003,0.175309,0.226163,0.203312,0.183967,lv
17,BIOBS004,0.149369,0.216096,0.203902,0.175161,nfv
18,BIOBS005,0.321428,0.306874,0.181600,0.313451,lv
19,BISE010,0.344276,0.293319,0.224601,0.322320,nfv
20,BISE011,0.331026,0.273870,0.181314,0.301096,nfv
21,BISE014,0.287707,0.250901,0.210449,0.236875,nfv
22,BISE019,0.356390,0.312632,0.186918,0.318399,nfv
0,BILP006,0.252843,0.267068,0.180211,0.256789,lv
1,BILP009,0.255348,0.257218,0.235588,0.244238,lv
2,BILP013,0.270008,0.254352,0.187814,0.240139,lv
3,BILP022,0.247419,0.254995,0.212980,0.225332,lv
4,BILP024,0.264987,0.243122,0.185527,0.232036,lv
5,BILP026,0.129812,0.208578,0.213508,0.134419,lv
6,BISE004,0.358015,0.266752,0.193700,0.309037,nfv
7,BISE005,0.312405,0.267560,0.189720,0.294423,nfv
8,BISE013,0.346783,0.311241,0.189339,0.297446,nfv
9,BISE016,0.303881,0.263507,0.202310,0.254975,nfv
10,BISE018,0.288640,0.303653,0.166332,0.273469,nfv

In [46]:
dominantTextSimDF.rename(columns={'Sample': 'Sample_ID'}, inplace=True)

In [47]:
dominantTextSimDF.columns

Index(['Sample_ID',
       '('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')',
       '('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')',
       '('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')',
       '('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')', 'Class'],
      dtype='object')

#Compare NDL vs DL for image-text congruence

In [48]:
dominantSpanishImageTextSimDF.shape

(11, 5)

In [49]:
dominantCatalanImageTextSimDF.shape

(23, 5)

In [59]:
dominantImageTextSimDF = pd.concat([dominantSpanishImageTextSimDF, dominantCatalanImageTextSimDF])
dominantImageTextSimDF.rename(columns={'Sample': 'Sample_ID'}, inplace=True)
dominantImageTextSimDF.head()

,Sample_ID,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP006_PreTx_Spa_WABPicnic_Coded.flo.cex,0.252843,0.267068,0.180211,0.256789
1,BILP009_PreTx_Spa_WABPicnic_Coded.flo.cex,0.255348,0.257218,0.235588,0.244238
2,BILP013_PreTx_Spa_WABPicnic_Coded.flo.cex,0.270008,0.254352,0.187814,0.240139
3,BILP022_PreTx_Spa_WABPicnic_Coded.flo.cex,0.247419,0.254995,0.212980,0.225332
4,BILP024_BACC016_PicnicScene_Spa_Pre_20240130_C...,0.264987,0.243122,0.185527,0.232036

In [51]:
notDominantSpanishImageTextSimDF.shape

(23, 5)

In [52]:
notDominantCatalanImageTextSimDF.shape

(11, 5)

In [58]:
notDominantImageTextSimDF = pd.concat([notDominantSpanishImageTextSimDF, notDominantCatalanImageTextSimDF])
notDominantImageTextSimDF.rename(columns={'Sample': 'Sample_ID'}, inplace=True)
notDominantImageTextSimDF.head()

,Sample_ID,"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')","('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')","('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')","('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')"
0,BILP007_PostTx_Spa_WABPicnic_Coded.flo.cex,0.269546,0.257789,0.237408,0.266129
1,BILP008_PreTx_Spa_WABPicnic_Coded.flo.cex,0.257092,0.276224,0.248163,0.266675
2,BILP010_PreTx_Spa_WABPicnic_Coded.flo.cex,0.231019,0.239711,0.215565,0.235069
3,BILP011_PreTx_Spa_WABPicnic_Coded.flo.cex,0.319062,0.271305,0.187178,0.300368
4,BILP012_PreTx_Spa_WABPicnic_Coded.flo.cex,0.287864,0.266844,0.187615,0.290993

In [60]:
domNonDomComparison(dominantImageTextSimDF, notDominantImageTextSimDF)

{"('ViT-B-16-plus-240', 'M-CLIP/XLM-Roberta-Large-Vit-B-16Plus')": 0.9498863502186063, "('ViT-B/32', 'M-CLIP/XLM-Roberta-Large-Vit-B-32')": 0.9498863502186063, "('ViT-L/14', 'M-CLIP/LABSE-Vit-L-14')": 0.10414661327045852, "('ViT-L/14', 'M-CLIP/XLM-Roberta-Large-Vit-L-14')": 0.9498863502186063}
Significant features: {}