#General McNemar code

In [1]:
import pandas as pd

In [2]:
def mcnemarEvaluation(y_target, y_model1, y_model2):
  import numpy as np
  from mlxtend.evaluate import mcnemar_table
  from mlxtend.evaluate import mcnemar
  y_target = np.array(y_target)
  y_model1 = np.array(y_model1)
  y_model2 = np.array(y_model2)
  tb = mcnemar_table(y_target=y_target,
                     y_model1=y_model1,
                     y_model2=y_model2)
  chi2, p = mcnemar(ary=tb, corrected=True,exact=True)
  print('chi-squared:', chi2)
  print('p-value:', p)
  return chi2, p

In [3]:
from sklearn.metrics import classification_report

#Non-dominant vs dominant

##Setup

In [4]:
import pandas as pd

In [5]:
from sklearn.metrics import classification_report

In [6]:
dominantDF = pd.read_csv('lvProbs_Dominant.csv')
nonDominantDF = pd.read_csv('lvProbs_NonDominant.csv')

In [7]:
dominantDF = dominantDF.sort_values(by=['Sample_ID'])
nonDominantDF = nonDominantDF.sort_values(by=['Sample_ID'])

In [8]:
assert list(dominantDF['Sample_ID']) == list(nonDominantDF['Sample_ID'])

In [9]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'
yTrue = list(nonDominantDF['Sample_ID'].apply(getClass))
print(yTrue)

['lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'nfv', 'lv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv']

In [10]:
from collections import Counter
Counter(yTrue)

Counter({'lv': 24, 'nfv': 10})

In [11]:
yTrue = [0 if y == 'nfv' else 1 for y in yTrue]
print(yTrue)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

##Image-text sim (p=0.73)

In [14]:
imageTextSimNonDomThreshold = 0.90#53497942386833
imageTextSimNonDomProbPred = list(nonDominantDF['Image-Text Sim: P(lv)'])
imageTextSimNonDomPredY = []
for prob in imageTextSimNonDomProbPred:
  if prob >= imageTextSimNonDomThreshold:
    imageTextSimNonDomPredY.append(1)
  else:
    imageTextSimNonDomPredY.append(0)
print(imageTextSimNonDomPredY)

[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]

In [15]:
#sanity check: matches original results
print(classification_report(yTrue, imageTextSimNonDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.80      0.80      0.80        10
          lv       0.92      0.92      0.92        24

    accuracy                           0.88        34
   macro avg       0.86      0.86      0.86        34
weighted avg       0.88      0.88      0.88        34

In [16]:
imageTextSimDomThresold = 0.437856997521382
imageTextSimDomProbPred = list(dominantDF['Image-Text Sim: P(lv)'])
imageTextSimDomPredY = []
for prob in imageTextSimDomProbPred:
  if prob >= imageTextSimDomThresold:
    imageTextSimDomPredY.append(1)
  else:
    imageTextSimDomPredY.append(0)
print(imageTextSimDomPredY)

[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0]

In [17]:
#sanity check: got the exact same results with rounded threshold
print(classification_report(yTrue, imageTextSimDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.78      0.70      0.74        10
          lv       0.88      0.92      0.90        24

    accuracy                           0.85        34
   macro avg       0.83      0.81      0.82        34
weighted avg       0.85      0.85      0.85        34

In [18]:
mcnemarEvaluation(yTrue, imageTextSimNonDomPredY, imageTextSimDomPredY) #new

chi-squared: None
p-value: 1.0

(None, np.float64(1.0))

##Speech-timing (p=0.58)

In [30]:
speechTimingNonDomThreshold = 0.0980392156862745
speechTimingNonDomProbPred = list(nonDominantDF['Speech Timing: P(lv)'])
speechTimingNonDomPredY = []
for prob in speechTimingNonDomProbPred:
  if prob >= speechTimingNonDomThreshold:
    speechTimingNonDomPredY.append(1)
  else:
    speechTimingNonDomPredY.append(0)
print(speechTimingNonDomPredY)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0]

In [31]:
#sanity check: matches with original output
print(classification_report(yTrue, speechTimingNonDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.86      0.60      0.71        10
          lv       0.85      0.96      0.90        24

    accuracy                           0.85        34
   macro avg       0.85      0.78      0.80        34
weighted avg       0.85      0.85      0.84        34

In [21]:
speechTimingDomThreshold = 0.7100961413889513
speechTimingDomProbPred = list(dominantDF['Speech-timing: P(lv)'])
speechTimingDomPredY = []
for prob in speechTimingDomProbPred:
  if prob >= speechTimingDomThreshold:
    speechTimingDomPredY.append(1)
  else:
    speechTimingDomPredY.append(0)
print(speechTimingDomPredY)

[1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]

In [22]:
#sanity check: matches with original output
print(classification_report(yTrue, speechTimingDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.50      0.90      0.64        10
          lv       0.94      0.62      0.75        24

    accuracy                           0.71        34
   macro avg       0.72      0.76      0.70        34
weighted avg       0.81      0.71      0.72        34

In [23]:
mcnemarEvaluation(yTrue, speechTimingNonDomPredY, speechTimingDomPredY)

chi-squared: None
p-value: 0.5810546875

(None, np.float64(0.5810546875))

##Word params (p=0.63)

In [32]:
nonDominantDF.columns

Index(['Sample_ID', 'Image-Text Sim: P(lv)', 'Speech Timing: P(lv)',
       'Word Ratings: P(lv)', 'Linguistic: P(lv)'],
      dtype='object')

In [33]:
wordParamsNonDomThreshold = 0.6161818867222746
wordParamsNonDomProbPred = list(nonDominantDF['Word Ratings: P(lv)'])
wordParamsNonDomPredY = []
for prob in wordParamsNonDomProbPred:
  if prob >= wordParamsNonDomThreshold:
    wordParamsNonDomPredY.append(1)
  else:
    wordParamsNonDomPredY.append(0)
print(wordParamsNonDomPredY)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [34]:
#sanity check: matches with original output
print(classification_report(yTrue, wordParamsNonDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.90      0.90      0.90        10
          lv       0.96      0.96      0.96        24

    accuracy                           0.94        34
   macro avg       0.93      0.93      0.93        34
weighted avg       0.94      0.94      0.94        34

In [35]:
wordParamsDomThreshold = 0.90#53497942386833
wordParamsDomProbPred = list(dominantDF['Word Ratings: P(lv)'])
wordParamsDomPredY = []
for prob in wordParamsDomProbPred:
  if prob >= wordParamsDomThreshold:
    wordParamsDomPredY.append(1)
  else:
    wordParamsDomPredY.append(0)
print(wordParamsDomPredY)

[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0]

In [36]:
print(classification_report(yTrue, wordParamsDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.80      0.80      0.80        10
          lv       0.92      0.92      0.92        24

    accuracy                           0.88        34
   macro avg       0.86      0.86      0.86        34
weighted avg       0.88      0.88      0.88        34

In [37]:
mcnemarEvaluation(yTrue, wordParamsNonDomPredY, wordParamsDomPredY) #new

chi-squared: None
p-value: 0.625

(None, np.float64(0.625))

##Linguistic (p=0.34)

In [38]:
lingNotDomThreshold = 0.95
lingNotDomProbPred = list(nonDominantDF['Linguistic: P(lv)'])
lingNotDomPredY = []
for prob in lingNotDomProbPred:
  if prob >= lingNotDomThreshold:
    lingNotDomPredY.append(1)
  else:
    lingNotDomPredY.append(0)
print(lingNotDomPredY)

[1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0]

In [39]:
#Sanity check passed
print(classification_report(yTrue, lingNotDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.58      0.70      0.64        10
          lv       0.86      0.79      0.83        24

    accuracy                           0.76        34
   macro avg       0.72      0.75      0.73        34
weighted avg       0.78      0.76      0.77        34

In [40]:
lingDomThreshold = 0.9103932558825174
lingDomProbPred = list(dominantDF['Linguistic: P(lv)'])
lingDomPredY = []
for prob in lingDomProbPred:
  if prob >= lingDomThreshold:
    lingDomPredY.append(1)
  else:
    lingDomPredY.append(0)
print(lingDomPredY)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [41]:
#sanity check passed!
print(classification_report(yTrue, lingDomPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.71      1.00      0.83        10
          lv       1.00      0.83      0.91        24

    accuracy                           0.88        34
   macro avg       0.86      0.92      0.87        34
weighted avg       0.92      0.88      0.89        34

In [42]:
mcnemarEvaluation(yTrue, lingDomPredY, lingNotDomPredY)

chi-squared: None
p-value: 0.34375

(None, np.float64(0.34375))

##Ensemble (p=1)

In [49]:
import numpy as np

In [50]:
ensembleNonDomSamples = ['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018', 'BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019']

In [51]:
ensembleNonDomPredProbs = [np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.4420372188605609), np.float64(0.5032674486644089), np.float64(0.566677265071236), np.float64(0.3265226742540188), np.float64(0.22627740619044232), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.9352423433136224), np.float64(0.37542850552971), np.float64(0.834450515691182), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.8150401949797746), np.float64(0.834450515691182), np.float64(0.8150401949797746), np.float64(0.8509181093010045), np.float64(0.4161572363851398), np.float64(0.22627740619044232), np.float64(0.05617494734242961), np.float64(0.8323346547753278), np.float64(0.22627740619044232)]

In [52]:
ensembleNonDomDict = dict(zip(ensembleNonDomSamples, ensembleNonDomPredProbs))

In [53]:
nonDomEnsembleDF = pd.DataFrame(list(ensembleNonDomDict.items()), columns=['Sample_ID', 'NonDom Ensemble: P(lv)'])
nonDomEnsembleDF.head()

  Sample_ID  NonDom Ensemble: P(lv)
0   BILP006                 0.81504
1   BILP009                 0.81504
2   BILP013                 0.81504
3   BILP022                 0.81504
4   BILP024                 0.81504

In [54]:
ensembleDomSamples =  ['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019', 'BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018']
ensembleDomPredProbs =  [np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.5126518622204566), np.float64(0.6386076596266459), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.6979285867780602), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445582240802092), np.float64(0.6173748848735733), np.float64(0.8902774953883139), np.float64(0.9445582240802092), np.float64(0.7606583068937436), np.float64(0.9648877576516085), np.float64(0.20268405292946312), np.float64(0.3104888463007177), np.float64(0.37377312744428476), np.float64(0.26019748137432575), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.6487903535696709), np.float64(0.6559231335489653), np.float64(0.26019748137432575), np.float64(0.22565055016729646), np.float64(0.26019748137432575), np.float64(0.8297316294482078), np.float64(0.2601974813743257)]
ensembleDomDict = dict(zip(ensembleDomSamples, ensembleDomPredProbs))
domEnsembleDF = pd.DataFrame(list(ensembleDomDict.items()), columns=['Sample_ID', 'Dom Ensemble: P(nfv)'])
domEnsembleDF.head()

  Sample_ID  Dom Ensemble: P(nfv)
0   BILP007              0.944588
1   BILP008              0.944588
2   BILP010              0.944588
3   BILP011              0.512652
4   BILP012              0.638608

In [55]:
domEnsembleDF = domEnsembleDF.sort_values(by=['Sample_ID'])
nonDomEnsembleDF = nonDomEnsembleDF.sort_values(by=['Sample_ID'])

In [56]:
ensembleDF = nonDomEnsembleDF.merge(domEnsembleDF, on='Sample_ID')
ensembleDF.head()

  Sample_ID  NonDom Ensemble: P(lv)  Dom Ensemble: P(nfv)
0   BILP006                 0.81504              0.944588
1   BILP007                 0.81504              0.944588
2   BILP008                 0.81504              0.944588
3   BILP009                 0.81504              0.944588
4   BILP010                 0.81504              0.944588

In [57]:
assert list(ensembleDF['Sample_ID']) == list(nonDominantDF['Sample_ID']) == list(dominantDF['Sample_ID'])
#means we can use yTrue from above

In [58]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [59]:
ensembleYTrue = list(ensembleDF['Sample_ID'].apply(getClass))

In [60]:
ensembleYTrue = [0 if y == 'nfv' else 1 for y in ensembleYTrue]
print(ensembleYTrue)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [61]:
from sklearn.metrics import classification_report

In [62]:
domEnsembleProbThreshold = 0.5126518622204566
domEnsemblePredY = []
for prob in list(ensembleDF['Dom Ensemble: P(nfv)']):
  if prob >= domEnsembleProbThreshold:
    domEnsemblePredY.append(1)
  else:
    domEnsemblePredY.append(0)
print(domEnsemblePredY)
print(classification_report(ensembleYTrue, domEnsemblePredY, target_names=['nfv','lv']))

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
              precision    recall  f1-score   support

         nfv       1.00      0.80      0.89        10
          lv       0.92      1.00      0.96        24

    accuracy                           0.94        34
   macro avg       0.96      0.90      0.92        34
weighted avg       0.95      0.94      0.94        34

In [63]:
nonDomEnsembleProbThreshold = 0.8150401949797746
nonDomEnsemblePredY = []
for prob in list(ensembleDF['NonDom Ensemble: P(lv)']):
  if prob >= nonDomEnsembleProbThreshold:
    nonDomEnsemblePredY.append(1)
  else:
    nonDomEnsemblePredY.append(0)
print(nonDomEnsemblePredY)
print(classification_report(ensembleYTrue, nonDomEnsemblePredY, target_names=['nfv','lv']))

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
              precision    recall  f1-score   support

         nfv       0.80      0.80      0.80        10
          lv       0.92      0.92      0.92        24

    accuracy                           0.88        34
   macro avg       0.86      0.86      0.86        34
weighted avg       0.88      0.88      0.88        34

In [64]:
mcnemarEvaluation(ensembleYTrue, nonDomEnsemblePredY, domEnsemblePredY)

chi-squared: None
p-value: 0.625

(None, np.float64(0.625))

##Best NDL vs DL (p=1)

best NDL classifier is word-level parameters

In [65]:
wordParamsNonDomThreshold = 0.6161818867222746
wordParamsNonDomProbPred = list(nonDominantDF['Word Ratings: P(lv)'])
wordParamsNonDomPredY = []
for prob in wordParamsNonDomProbPred:
  if prob >= wordParamsNonDomThreshold:
    wordParamsNonDomPredY.append(1)
  else:
    wordParamsNonDomPredY.append(0)
print(wordParamsNonDomPredY)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [66]:
wordParamNonDomSamples = list(nonDominantDF['Sample_ID'])
wordParamsNonDomProbPred = list(nonDominantDF['Word Ratings: P(lv)'])
wordParamsNonDomDict = dict(zip(wordParamNonDomSamples, wordParamsNonDomProbPred))
wordParamsNonDomDF = pd.DataFrame(list(wordParamsNonDomDict.items()), columns=['Sample_ID', 'Word Params: P(lv)'])
wordParamsNonDomDF.head()

  Sample_ID  Word Params: P(lv)
0   BILP006            0.686828
1   BILP007            0.794195
2   BILP008            0.831501
3   BILP009            0.792514
4   BILP010            0.788754

best DL classifier is ensemble classifier

In [67]:
import numpy as np

In [68]:
ensembleDomSamples =  ['BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019', 'BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018']
ensembleDomPredProbs =  [np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.5126518622204566), np.float64(0.6386076596266459), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.6979285867780602), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445582240802092), np.float64(0.6173748848735733), np.float64(0.8902774953883139), np.float64(0.9445582240802092), np.float64(0.7606583068937436), np.float64(0.9648877576516085), np.float64(0.20268405292946312), np.float64(0.3104888463007177), np.float64(0.37377312744428476), np.float64(0.26019748137432575), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.9445880390622088), np.float64(0.6487903535696709), np.float64(0.6559231335489653), np.float64(0.26019748137432575), np.float64(0.22565055016729646), np.float64(0.26019748137432575), np.float64(0.8297316294482078), np.float64(0.2601974813743257)]
ensembleDomDict = dict(zip(ensembleDomSamples, ensembleDomPredProbs))
domEnsembleDF = pd.DataFrame(list(ensembleDomDict.items()), columns=['Sample_ID', 'Dom Ensemble: P(nfv)'])
domEnsembleDF.head()

  Sample_ID  Dom Ensemble: P(nfv)
0   BILP007              0.944588
1   BILP008              0.944588
2   BILP010              0.944588
3   BILP011              0.512652
4   BILP012              0.638608

In [69]:
#sort by Sample_ID
wordParamsNonDomDF = wordParamsNonDomDF.sort_values(by=['Sample_ID'])
domEnsembleDF = domEnsembleDF.sort_values(by=['Sample_ID'])
assert list(wordParamsNonDomDF['Sample_ID']) == list(domEnsembleDF['Sample_ID'])

In [70]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [71]:
bestYTrue = list(domEnsembleDF['Sample_ID'].apply(getClass))
bestYTrue = [0 if y == 'nfv' else 1 for y in bestYTrue]

In [72]:
domEnsembleProbThreshold = 0.5126518622204566
domEnsemblePredY = []
for prob in list(domEnsembleDF['Dom Ensemble: P(nfv)']):
  if prob >= domEnsembleProbThreshold:
    domEnsemblePredY.append(1)
  else:
    domEnsemblePredY.append(0)
print(domEnsemblePredY)
print(classification_report(bestYTrue, domEnsemblePredY, target_names=['nfv','lv'])) #sanity check passed

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
              precision    recall  f1-score   support

         nfv       1.00      0.80      0.89        10
          lv       0.92      1.00      0.96        24

    accuracy                           0.94        34
   macro avg       0.96      0.90      0.92        34
weighted avg       0.95      0.94      0.94        34

In [74]:
wordParamsNonDomThreshold = 0.6161818867222746
wordParamsNonDomProbPred = list(wordParamsNonDomDF['Word Params: P(lv)'])
wordParamsNonDomPredY = []
for prob in wordParamsNonDomProbPred:
  if prob >= wordParamsNonDomThreshold:
    wordParamsNonDomPredY.append(1)
  else:
    wordParamsNonDomPredY.append(0)
print(wordParamsNonDomPredY)

[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [75]:
#sanity check: classification performance of NDL word param classifier
print(classification_report(bestYTrue, wordParamsNonDomPredY, target_names=['nfv','lv'])) #passed!

              precision    recall  f1-score   support

         nfv       0.90      0.90      0.90        10
          lv       0.96      0.96      0.96        24

    accuracy                           0.94        34
   macro avg       0.93      0.93      0.93        34
weighted avg       0.94      0.94      0.94        34

In [76]:
mcnemarEvaluation(bestYTrue, wordParamsNonDomPredY, domEnsemblePredY)

chi-squared: None
p-value: 1.0

(None, 1.0)

#Spanish vs Catalan

##setup

In [77]:
spanishDF = pd.read_csv('lvProbs_Spa.csv')
catalanDF = pd.read_csv('lvProbs_Cat.csv')

In [78]:
spanishDF = spanishDF.sort_values(by=['Sample_ID'])
catalanDF = catalanDF.sort_values(by=['Sample_ID'])

In [79]:
spanishDF.head()

,Sample_ID,Image-Text Sim: P(lv),Acoustic: P(lv),Word Ratings: P(lv),Linguistic: P(lv)
0,BILP006,0.194553,0.884057,0.615455,0.913043
11,BILP007,0.896861,0.744490,0.927325,0.913043
12,BILP008,0.194553,0.619564,0.911112,0.954545
1,BILP009,0.896861,0.842635,0.897462,0.913043
13,BILP010,0.896861,0.854721,0.928481,0.954545

In [80]:
catalanDF.head()

,Sample_ID,Image-Text Sim: P(lv),Speech timing: P(lv),Word Ratings: P(lv),Linguistic: P(lv)
0,BILP006,0.688152,0.956615,0.901288,0.845334
11,BILP007,0.602268,0.919800,0.901288,0.775944
12,BILP008,0.235272,0.980823,0.901288,0.801166
1,BILP009,0.438279,0.460747,0.901288,0.760483
13,BILP010,0.829068,0.951715,0.901288,0.829315

In [81]:
assert list(spanishDF['Sample_ID']) == list(catalanDF['Sample_ID'])

In [82]:
def getClass(filename):
  if 'BISE' in filename:
    return 'nfv'
  if 'BILP' in filename:
    return 'lv'
  if 'BIOBS003' in filename or 'BIOBS005' in filename:
    return 'lv'
  if 'BIOBS004' in filename:
    return 'nfv'

In [83]:
yTrue = list(catalanDF['Sample_ID'].apply(getClass))
print(yTrue)

['lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'lv', 'nfv', 'lv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv', 'nfv']

In [84]:
from collections import Counter
Counter(yTrue)

Counter({'lv': 24, 'nfv': 10})

In [85]:
yTrue = [0 if y == 'nfv' else 1 for y in yTrue]
print(yTrue)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

##image-text sim (p=1)

In [88]:
imageTextSimSpaThreshold = 0.126#58227848101264
imageTextSimSpaProbPred = list(spanishDF['Image-Text Sim: P(lv)'])
imageTextSimSpaPredY = []
for prob in imageTextSimSpaProbPred:
  if prob >= imageTextSimSpaThreshold:
    imageTextSimSpaPredY.append(1)
  else:
    imageTextSimSpaPredY.append(0)
print(imageTextSimSpaPredY)

[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]

In [89]:
#sanity check passed
print(classification_report(yTrue, imageTextSimSpaPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.73      0.80      0.76        10
          lv       0.91      0.88      0.89        24

    accuracy                           0.85        34
   macro avg       0.82      0.84      0.83        34
weighted avg       0.86      0.85      0.85        34

In [92]:
imageTextSimCatThreshold = 0.4382792401801251
imageTextSimCatProbPred = list(catalanDF['Image-Text Sim: P(lv)'])
imageTextSimCatPredY = []
for prob in imageTextSimCatProbPred:
  if prob >= imageTextSimCatThreshold:
    imageTextSimCatPredY.append(1)
  else:
    imageTextSimCatPredY.append(0)
print(imageTextSimCatPredY)
#sanity check NOT passed
print(classification_report(yTrue, imageTextSimCatPredY, target_names=['nfv','lv']))

[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
              precision    recall  f1-score   support

         nfv       0.73      0.80      0.76        10
          lv       0.91      0.88      0.89        24

    accuracy                           0.85        34
   macro avg       0.82      0.84      0.83        34
weighted avg       0.86      0.85      0.85        34

In [93]:
mcnemarEvaluation(yTrue, imageTextSimSpaPredY, imageTextSimCatPredY)

chi-squared: None
p-value: 1.0

(None, 1.0)

##speech-timing (p=1)

In [94]:
catalanDF.columns

Index(['Sample_ID', 'Image-Text Sim: P(lv)', 'Speech timing: P(lv)',
       'Word Ratings: P(lv)', 'Linguistic: P(lv)'],
      dtype='object')

In [95]:
speechTimingCatThreshold = 0.769775091956701
speechTimingCatProbPred = list(catalanDF['Speech timing: P(lv)'])
speechTimingCatPredY = []
for prob in speechTimingCatProbPred:
  if prob >= speechTimingCatThreshold:
    speechTimingCatPredY.append(1)
  else:
    speechTimingCatPredY.append(0)
print(speechTimingCatPredY)

[1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [96]:
#sanity check: same output as original output PASSED
print(classification_report(yTrue, speechTimingCatPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.56      1.00      0.71        10
          lv       1.00      0.67      0.80        24

    accuracy                           0.76        34
   macro avg       0.78      0.83      0.76        34
weighted avg       0.87      0.76      0.77        34

In [97]:
spanishDF.columns

Index(['Sample_ID', 'Image-Text Sim: P(lv)', 'Acoustic: P(lv)',
       'Word Ratings: P(lv)', 'Linguistic: P(lv)'],
      dtype='object')

In [98]:
speechTimingSpaThreshold = 0.7444902345161638
speechTimingSpaProbPred = list(spanishDF['Acoustic: P(lv)'])
speechTimingSpaPredY = []
for prob in speechTimingSpaProbPred:
  if prob >= speechTimingSpaThreshold:
    speechTimingSpaPredY.append(1)
  else:
    speechTimingSpaPredY.append(0)
print(speechTimingSpaPredY)

[1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

In [99]:
#sanity check passed
print(classification_report(yTrue, speechTimingSpaPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.56      0.90      0.69        10
          lv       0.94      0.71      0.81        24

    accuracy                           0.76        34
   macro avg       0.75      0.80      0.75        34
weighted avg       0.83      0.76      0.78        34

In [100]:
mcnemarEvaluation(yTrue, speechTimingCatPredY, speechTimingSpaPredY)

chi-squared: None
p-value: 1.0

(None, 1.0)

##word params (p=1)

In [101]:
spanishDF.columns

Index(['Sample_ID', 'Image-Text Sim: P(lv)', 'Acoustic: P(lv)',
       'Word Ratings: P(lv)', 'Linguistic: P(lv)'],
      dtype='object')

In [102]:
wordParamsSpaThreshold = 0.5872960826961688
wordParamsSpaProbPred = list(spanishDF['Word Ratings: P(lv)'])
wordParamsSpaPredY = []
for prob in wordParamsSpaProbPred:
  if prob >= wordParamsSpaThreshold:
    wordParamsSpaPredY.append(1)
  else:
    wordParamsSpaPredY.append(0)
print(wordParamsSpaPredY)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0]

In [103]:
#PASSED SANITY CHECK
print(classification_report(yTrue, wordParamsSpaPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.88      0.70      0.78        10
          lv       0.88      0.96      0.92        24

    accuracy                           0.88        34
   macro avg       0.88      0.83      0.85        34
weighted avg       0.88      0.88      0.88        34

In [104]:
wordParamsCatThreshold = 0.9012875536480688
wordParamsCatProbPred = list(catalanDF['Word Ratings: P(lv)'])
wordParamsCatPredY = []
for prob in wordParamsCatProbPred:
  if prob >= wordParamsCatThreshold:
    wordParamsCatPredY.append(1)
  else:
    wordParamsCatPredY.append(0)
print(wordParamsCatPredY)

[1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [105]:
#PASSED Sanity check
print(classification_report(yTrue, wordParamsCatPredY,target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.75      0.90      0.82        10
          lv       0.95      0.88      0.91        24

    accuracy                           0.88        34
   macro avg       0.85      0.89      0.87        34
weighted avg       0.89      0.88      0.89        34

In [106]:
mcnemarEvaluation(yTrue, wordParamsSpaPredY, wordParamsCatPredY)

chi-squared: None
p-value: 1.0

(None, 1.0)

##linguistic (p=0.45)

In [107]:
catalanDF.columns

Index(['Sample_ID', 'Image-Text Sim: P(lv)', 'Speech timing: P(lv)',
       'Word Ratings: P(lv)', 'Linguistic: P(lv)'],
      dtype='object')

In [108]:
lingCatThreshold = 0.7334625598584378
lingCatProbPred = list(catalanDF['Linguistic: P(lv)'])
lingCatPredY = []
for prob in lingCatProbPred:
  if prob >= lingCatThreshold:
    lingCatPredY.append(1)
  else:
    lingCatPredY.append(0)
print(lingCatPredY)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0]

In [109]:
#PASSED Sanity check
print(classification_report(yTrue, lingCatPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.67      0.60      0.63        10
          lv       0.84      0.88      0.86        24

    accuracy                           0.79        34
   macro avg       0.75      0.74      0.74        34
weighted avg       0.79      0.79      0.79        34

In [110]:
lingSpaThreshold = 0.9130434782608695
lingSpaProbPred = list(spanishDF['Linguistic: P(lv)'])
lingSpaPredY = []
for prob in lingSpaProbPred:
  if prob >= lingSpaThreshold:
    lingSpaPredY.append(1)
  else:
    lingSpaPredY.append(0)
print(lingSpaPredY)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0]

In [111]:
#PASSED sanity check
print(classification_report(yTrue, lingSpaPredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.80      0.80      0.80        10
          lv       0.92      0.92      0.92        24

    accuracy                           0.88        34
   macro avg       0.86      0.86      0.86        34
weighted avg       0.88      0.88      0.88        34

In [112]:
mcnemarEvaluation(yTrue, lingCatPredY, lingSpaPredY)

chi-squared: None
p-value: 0.453125

(None, np.float64(0.453125))

##ensemble (p=1)

In [115]:
spaEnsembleIDs = ['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018', 'BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019']
spaEnsemblePredProbs = [np.float64(0.6104991450053525), np.float64(0.5896500279206671), np.float64(0.5930459916632194), np.float64(0.552445126725894), np.float64(0.5943424517504703), np.float64(0.2627348331392363), np.float64(0.34182458684417044), np.float64(0.35370364969530416), np.float64(0.32114264149053084), np.float64(0.5528316614303459), np.float64(0.1661905141246863), np.float64(0.5452330912629485), np.float64(0.49044933008282976), np.float64(0.6063829800214882), np.float64(0.6605349872854078), np.float64(0.4875332639768565), np.float64(0.6101968990965052), np.float64(0.22859433158443015), np.float64(0.5543969984882213), np.float64(0.5784187736135006), np.float64(0.5921954188254204), np.float64(0.5905781921492363), np.float64(0.5215601407401141), np.float64(0.6069829009150979), np.float64(0.37019546057647995), np.float64(0.5401784737456261), np.float64(0.1453410359450012), np.float64(0.6070183699177261), np.float64(0.17780493647394166), np.float64(0.1742345920791284), np.float64(0.211312181960257), np.float64(0.1686559934192779), np.float64(0.171226151574573), np.float64(0.1696919542106599)]
spaEnsembleDict = dict(zip(spaEnsembleIDs, spaEnsemblePredProbs))

In [116]:
spaEnsembleDF = pd.DataFrame(list(spaEnsembleDict.items()), columns=['Sample_ID', 'Spa: P(lv)'])
spaEnsembleDF.head()

  Sample_ID  Spa: P(lv)
0   BILP006    0.610499
1   BILP009    0.589650
2   BILP013    0.593046
3   BILP022    0.552445
4   BILP024    0.594342

In [117]:
catEnsembleIDs = ['BILP006', 'BILP009', 'BILP013', 'BILP022', 'BILP024', 'BILP026', 'BISE004', 'BISE005', 'BISE013', 'BISE016', 'BISE018', 'BILP007', 'BILP008', 'BILP010', 'BILP011', 'BILP012', 'BILP014', 'BILP015', 'BILP017', 'BILP018', 'BILP019', 'BILP020', 'BILP021', 'BILP025', 'BILP027', 'BILP028', 'BILP029', 'BIOBS003', 'BIOBS004', 'BIOBS005', 'BISE010', 'BISE011', 'BISE014', 'BISE019']
catEnsemblePredProbs = [np.float64(0.8663142038830283), np.float64(0.7500797637660881), np.float64(0.8693767037160212), np.float64(0.738109063332512), np.float64(0.8780695738642074), np.float64(0.8616800706231407), np.float64(0.42420409446136437), np.float64(0.35062651332056527), np.float64(0.633614359879693), np.float64(0.8973109121447489), np.float64(0.3409110841264633), np.float64(0.8528663619017963), np.float64(0.774654171621658), np.float64(0.881101776505966), np.float64(0.20789639202071536), np.float64(0.7987953300165292), np.float64(0.3499856575313131), np.float64(0.8459962775704257), np.float64(0.839061911438302), np.float64(0.8421784090021901), np.float64(0.7973794595991444), np.float64(0.8583013137701914), np.float64(0.8656509132495327), np.float64(0.8521745258935363), np.float64(0.8127356097087408), np.float64(0.3902198126595835), np.float64(0.6619706046962555), np.float64(0.8672817346423922), np.float64(0.9354024650722507), np.float64(0.6551355808193701), np.float64(0.38340507840326193), np.float64(0.5065664344412579), np.float64(0.513355669978034), np.float64(0.5064305270637193)]
catEnsembleDict = dict(zip(catEnsembleIDs, catEnsemblePredProbs))

In [118]:
catEnsembleDF = pd.DataFrame(list(catEnsembleDict.items()), columns=['Sample_ID', 'Cat: P(lv)'])
catEnsembleDF.head()

  Sample_ID  Cat: P(lv)
0   BILP006    0.866314
1   BILP009    0.750080
2   BILP013    0.869377
3   BILP022    0.738109
4   BILP024    0.878070

In [119]:
ensembleDF = spaEnsembleDF.merge(catEnsembleDF, on='Sample_ID')
ensembleDF.head()

  Sample_ID  Spa: P(lv)  Cat: P(lv)
0   BILP006    0.610499    0.866314
1   BILP009    0.589650    0.750080
2   BILP013    0.593046    0.869377
3   BILP022    0.552445    0.738109
4   BILP024    0.594342    0.878070

In [120]:
ensembleYTrue = list(ensembleDF['Sample_ID'].apply(getClass))

In [121]:
from collections import Counter
Counter(ensembleYTrue)

Counter({'lv': 24, 'nfv': 10})

In [122]:
ensembleYTrue = [0 if y == 'nfv' else 1 for y in ensembleYTrue]
print(ensembleYTrue)

[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0]

In [124]:
spaEnsemblePredProbs = list(ensembleDF['Spa: P(lv)'])
spaEnsembleThreshold = 0.37019546057647995
spaEnsemblePredY = []
for prob in spaEnsemblePredProbs:
  if prob >= spaEnsembleThreshold:
    spaEnsemblePredY.append(1)
  else:
    spaEnsemblePredY.append(0)
print(spaEnsemblePredY)

[1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0]

In [125]:
#passed sanity check
print(classification_report(ensembleYTrue, spaEnsemblePredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.69      0.90      0.78        10
          lv       0.95      0.83      0.89        24

    accuracy                           0.85        34
   macro avg       0.82      0.87      0.84        34
weighted avg       0.88      0.85      0.86        34

In [126]:
catEnsemblePredProbs = list(ensembleDF['Cat: P(lv)'])
catEnsembleThreshold = 0.6551355808193701
catEnsemblePredY = []
for prob in catEnsemblePredProbs:
  if prob >= catEnsembleThreshold:
    catEnsemblePredY.append(1)
  else:
    catEnsemblePredY.append(0)
print(catEnsemblePredY)

[1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0]

In [127]:
#passed sanity check
print(classification_report(ensembleYTrue, catEnsemblePredY, target_names=['nfv','lv']))

              precision    recall  f1-score   support

         nfv       0.73      0.80      0.76        10
          lv       0.91      0.88      0.89        24

    accuracy                           0.85        34
   macro avg       0.82      0.84      0.83        34
weighted avg       0.86      0.85      0.85        34

In [128]:
mcnemarEvaluation(ensembleYTrue, spaEnsemblePredY,catEnsemblePredY)

chi-squared: None
p-value: 1.0

(None, 1.0)